### ISSUE TITLE
strictEviction does not disable chunking

### ISSUE THREAD

**Issue by ben-manes** [cache2k/cache2k#104]
I noticed this by accident when simulating the P8 trace at `65536`. The reported eviction count didn't make sense, which is maintained separately from cache's stats to avoid product-specific bugs. In this run there were 21M misses and 1.9M evictions, whereas they should differ by roughly `maximumSize`. That incremented the `evictionCount` whenever `maximumSize == cache.asMap().size()`, which naively assumed prompt eviction.

I noticed that I hadn't enable `strictEviction`, but setting this didn't fix the problem. That configuration ensures that only 1 segment is used, but it is not passed through to `AbstractEviction` to disable chunking. It seems that chunking is enabled regardless of the user-specified configuration, as it is based on the `maxSize` and cpu count. In this case the chunk size is `11` causing the efficiency report to be incorrect and the hit rates biased. The simulator definition is [here](https://github.com/ben-manes/caffeine/blob/91eec88be93f16549ce82dd2f17959fd8eba75dd/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/Cache2kPolicy.java) if you have further suggestions on the configuration.

https://github.com/cache2k/cache2k/blob/4aa15eb1a2c7ebf3bcf11136b868d77de62dcad5/cache2k-core/src/main/java/org/cache2k/core/AbstractEviction.java#L63-L68

```java
/**
 * To increase performance cache2k optimizes the eviction and does eviction in
 * greater chunks. With strict eviction, the eviction is done for one entry
 * as soon as the capacity constraint is met. This is primarily used for
 * testing and evaluation purposes.
 */
```

**Comment by cruftex** [comment]
Thanks, Ben! It makes sense to disable the chunking optimization for the eviction tests.
In case you do further tests, I can release a quick fix.

About your simulator code:

````
  public void record(long key) {
    Object value = cache.peek(key);
    if (value == null) {
      policyStats.recordMiss();
      if (cache.asMap().size() == maximumSize) {
        policyStats.recordEviction();
      }
      cache.put(key, key);
    } else {
      policyStats.recordHit();
    }
  }
````

I think the assumption that eviction happens only when the cache reached its maximum capacity isn't working consistently for other caches as well. What about making the simulator code agnostic to the cache eviction semantics?

A separate unbounded map or set, could keep track of the keys that are stored. In case the entry was stored before, but is not present any more, an eviction must have occurred.

**Comment by ben-manes** [comment]
There is no rush, I was playing with tuning the adaptivity and saw an odd number when scanning the report. It was by chance and has no impact.

I don't believe cache2k has an eviction listener, correct? That's how I handle it for [GuavaPolicy](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/GuavaPolicy.java) since it will evict early, so simple assumption won't hold.

The eviction count should be (misses - size), so it is helpful to verify the implementation works how I expected to ensure my reports are honest / accurate. If the numbers are off then I know to look deeper into how it works to ensure the hit rate is correct (or document if not possible, like tcache's watermarking). The adapter for cache2k probably worked right originally, but of course you've done a ton of work on it since then and I overlooked configuration changes.

Anyway, doesn't affect me nor do I have write up planned, so you can throw this in your backlog and release it whenever that happens naturally.
