### ISSUE TITLE
Atomic Operations on multiple items

### ISSUE THREAD

**Issue by hc-codersatlas** [cache2k/cache2k#105]
Hi, what would be the best way for a scenario, say e.g. I have a Team that has many Players. The Players are cached with Cache2K. Sometimes more than 1 player leaves and I need to remove or replace this atomically. Is there a way to access the internal locks or similar to make this happen? i.e. otherwise it reads an incomplete state.

**Comment by cruftex** [comment]
Depending on how you structure the data, you need to do different approaches for the operation, or, vice versa, you need to structure the data according to the operations available.

Basically you can do an atomic operation on one cache entry. If you want to do an atomic operation on multiple cache you need to do some extra locking, via the usual Java mechanisms. The operations available in cache2k are similar to other caches and maps and are documented here:
https://cache2k.org/docs/latest/user-guide.html#atomic-operations

I assume that "team" and "players" is just a placeholder. But in case its actually really on the business level, then it would be better solved with a database and transactions.

For a cache or map it boils down to:
1. Put all information regarding a team in one cache entry
2. Maintain a separate lock e.g. per team

**Comment by hc-codersatlas** [comment]
Ok, thanks. Yes, those are just the placeholders. all good.
