### ISSUE TITLE
Simultaneous access

### ISSUE THREAD

**Issue by Devan-Kerman** [cache2k/cache2k#107]
Is there a way I could add a custom loader that would allow me to access the cache from multiple threads at the same time, and if they were accessing different keys, they would not block each other?

**Comment by cruftex** [comment]
In the loader cache2k locks on the entry or the key the loader is operating on and blocks all other operations on that key within the cache. That said, it is possible to operate on other keys of the cache, but in case they in turn depend on the current key you end up in a deadlock situation.

Usually, whenever I have operations on multiple keys in our applications, we have some mitigation strategies for deadlocks, either by having a defined lock order and/or a deadlock detection.

The loader pattern is designed to generate the value of one key only.

A requirement like yours always has a bit of a smell and I would be curious whether there might be a different approach to it. Can you give a little bit more details on the data structures you are operating on?

**Comment by Devan-Kerman** [comment]
It's a wrapper for an API, right now I am caching the returned object (after gson and my wrapper has done it's work) and the key being the URL, when someone uses the library, say to getSomething(valx) it assembles the URL and retrieves it from the cache, if it's not found it goes to the loader to get a new object from the API. I want to be able to wait on other requests of the same url, so it doesn't do the same thing twice, but not block other operations requesting different data from a different part of the api. This is what my (very very very) crude test looks like:
```java
Cache<String, char[]> test;
Cache2kBuilder<String, char[]> builder = new Cache2kBuilder<String, char[]>() {};
AtomicInteger atomint = new AtomicInteger();
test = builder.loader(s -> {
	atomint.incrementAndGet();
	System.out.println("Active: " + atomint); // This always prints 1
	char[] pre = s.toCharArray();
	for(int x = 0; x < pre.length; x++)
		pre[x] = (char) (pre[x]^'_'); // Random operations to slow the loader down.
	Thread.sleep(100);
	atomint.decrementAndGet();
	return pre;
}).build();
long start = System.currentTimeMillis();
test.get("wedawdwedawdawdawdsrdwedawdawdawdsrdawdawdsrd");
test.get("waawdawwedawdawdawdsrdwedawdawdawdsrddawdawdawd");
test.get("wesdwedawdawdawdsrdwedawdawdawdsrdawdawdrd");
test.get("weawwedawdawdawdsrdwedawdawdawdsrddawdawadwawdawsrd");
test.get("weswedawdawdawdsrdwedawdawdawdsrddawdawdawdrd");
test.get("wedwedawdawdawdsrdwedawdawdawdsrdadawdasrd");
test.get("wawwedawdawdawdsrdwedawdawdawdsrddawdesrd");
test.get("wedwedawdawdawdsrdwedawdawdawdsrdawdawdawdawsrd");
test.get("wedawdawdawdsrdwedawdawdawdsrdwedawdawdawdsrd");
test.get("wedawdawdawdsrdwedawdawdawdsrdwedawdawdawdsrd");
test.get("wedawwedawdawdawdsrdwedawdawdawdsrdwedawdawdawdsrddawdasrd");
test.get("wedawwedawdawdawdsrdwedawdawdawdsrddawdawsrd");
test.get("weawdwedawdawdawdsrdwedawdawdawdsrdawdawdawsrd");
test.get("weswdwedawdawdawdsrdwedawdawdawdsrdawdawdawrd");
test.get("wesrdawwedawdawdawdsrdwedawdawdawdsrddawdawdawdd");
test.get("wesdawwedawdawdawdsrdwedawdawdawdsrddawdawdrd");
test.get("wedawwedawdawdawdsrdwedawdawdawdsrddawdawsrd");
test.get("weawdwedawdawdawdsrdwedawdawdawdsrdawdawdawsrd");
test.get("weawdwedawdawdawdsrdwedawdawdawdsrdawdawdsrd");
test.get("weawdawdawdawwedawdawdawdsrdwedawdawdawdsrddawdawdsrd");
test.get("wesawdawwedawdawdawdsrdwedawdawdawdsrddawdawrd");
test.get("wedawdawwedawdawdawdsrdwedawdawdawdsrddawdawdsrd");
test.get("weawdawedawdawdawdsrdwedawdawdawdsrdwdawdawdsrd");
System.out.printf("Time: %d", System.currentTimeMillis()-start);
```
this something that simulates what I'm trying to do
```java
Set<String> current = new ConcurrentSkipListSet<>();
public <T> T getObject(String url) {
	while(true)
		if(!current.contains(url))
			break;
		current.add(url);
	T t;
	//Some operations
	current.remove(url);
	return t;
}
```
and this is what I have currently
```java
RLong size = new RLong(); // Replace with atomic long if non-blocking
cache = cacheBuilder.loader(this::get).expireAfterWrite(amount, unit)
				.addAsyncListener((CacheEntryCreatedListener<CacheEntry<?>, Object>) (cacheinst, entry) -> {
					CacheEntry<?> key = entry.getKey();
					Object value = entry.getValue();
					long sizeof = UnsafeUtil.deepSizeOf(value);
					if (size.plus(sizeof) > cachesize)
						cacheinst.remove(key);
				}).addAsyncListener((CacheEntryExpiredListener<CacheEntry<?>, Object>) (cacheinst, entry) -> size
						.preDec(UnsafeUtil.deepSizeOf(entry.getValue())))
				.build();
```

**Comment by Devan-Kerman** [comment]
Is there a way I could disable the lock for the cache, and implement my own? (via some wrapper object/methods)

**Comment by cruftex** [comment]
@Devan-Kerman, it seems to me that all of this is not necessary. The locking in the cache is actually providing the semantics you like to achieve, I think.

> I want to be able to wait on other requests of the same url, so it doesn't do the same thing twice, but not block other operations requesting different data from a different part of the api.

That is actually a basic feature of cache2k, see:
https://stackoverflow.com/questions/41374834/cache2k-read-through-and-blocking

**Comment by Devan-Kerman** [comment]
So even if I accessed 2 urls at the same time, it would not block either operation, unless they were the same url? The test above always printed one, idealy it would print 2, 5 or some other number, because all of them were different keys

**Comment by cruftex** [comment]
> So even if I accessed 2 urls at the same time, it would not block either operation, unless they were the same url?

> The test above always printed one, idealy it would print 2, 5 or some other number, because all of them were different keys

Yes, because `cache.get()` retrieves and item from the cache. For each operation on a new distinct URL it has to wait until the loader completes. Your test code runs sequentially. You could use e.g. `cache.loadAll()` to run the loader in parallel.

**Comment by Devan-Kerman** [comment]
Ah never mind, yea I just realized my test was flawed, thank you.

**Comment by cruftex** [comment]
No problem, you are welcome!

Based on your recent experience, maybe you can give feedback where I can improve the documentation or maybe scenarios that should be covered for introductions?
