### ISSUE TITLE
Cannot set default manager name via CacheManager.setDefaultName

### ISSUE THREAD

**Issue by frederikb** [cache2k/cache2k#108]
Hi,

small bug which we found while test driving Cache2k with JMX enabled in JEE application server.

**Version**: Running `1.2.1.Final`

**Scenario:** 
We want to change the default cache manager name for the current application before any cache is accessed.

**Expectation:**
Calling `CacheManager.setDefaultName` early will register the given name.

**Observation:**
An `UnsupportedOperationException` is thrown, coming out of `EmptyMap/AbstractMap.put`.

**Reason:**
 `Cache2kCoreProviderImpl` initializes `loader2defaultName` with `Collection.emptyMap`. This map implementation is immutable and therefore the `put` modification done in `Cache2kCoreProviderImpl.setDefaultManagerName` fails. 

The field is overwritten with a `WeakHashMap` as soon as `getDefaultManagerName` is called but then we're not allowed to change the cache manager name anymore.

**Workaround**:
Setting the cache manager name via XML works as desired.

**Comment by cruftex** [comment]
@frederikb Many thanks for the detailed bug report! 
If that is not critical for anybody I'll plan to fix that on the next feature release but not on the last stable 1.2.x.

**Comment by frederikb** [comment]
Hi @cruftex forgetting back to me. Sure thing, the workaround is fine for now.
