### ISSUE TITLE
Add cache2k ability to run on projects that do not use ProGuard

### ISSUE THREAD

**Issue by miguelarc95** [cache2k/cache2k#110]
I was trying to add cache2k to my project (which doesn't uses proguard), and I was getting `java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/InitialContext`. This is because I don't have the ability to set proguard rules to my project (proguard is disabled), and can't strip missing JMX dependencies out. 
I've also commented this issue [here](https://stackoverflow.com/a/54664804/7671879)
I understand the need of making the jar as small as possible, but this makes the project dependent on having proguard enabled.

**Comment by cruftex** [comment]
Sorry, I somehow missed that issue. Its almost a duplicate of https://github.com/cache2k/cache2k/issues/102

I released version 1.2.3.Final 6 days ago that fixes that problem. It runs on Android without the need to user ProGuard

**Comment by miguelarc95** [comment]
Maybe it's something with github notifications because I wasn't notified of your reply either.
Thanks for the reply, and for fixing the issue 👍
