### ISSUE TITLE
Integer overflow when the amount of element overtakes 2^25

### ISSUE THREAD

**Issue by detohaz** [cache2k/cache2k#111]
Take a look at method cache2k-api\Hash2.java:Hash2<K,V>->calcMaxFill(), you should be noticed that there is an Integer Overflow side effect here. When the amount of element overtakes 2^24 and HeapCache.TUNABLE.hashLoadPercent value is default (64), doubling the hash table size to 2^25 causes segmentMaxFill to negative (and 0 for the latter, which causes NegativeArraySizeException) because of Integer Overflow. 

I've rebuilded your library with an adjustment for calcMaxFill method:
"Math.round((float)entries.length * HeapCache.TUNABLE.hashLoadPercent / 100 / LOCK_SEGMENTS);" and it works like a charm.

Your friend,
H.B Xuyen

**Comment by cruftex** [comment]
@detohaz: Many thanks for the bug report!
Probably I never did test with that many entries. What is the heap size and cache size of your application?

**Comment by detohaz** [comment]
I'm sorry that I didn't pay much attention to heap size and cache size cause I only care where the problem comes from (your expression to calculate segmentMaxFill) and how to fix it. May be it's redundant but I would like to attach an explanation here with hashLoadPercent = 64 and LOCK_SEGMENTS = 64 too (my case).
![Capture](https://user-images.githubusercontent.com/9496595/56404898-91f55600-6293-11e9-9d79-417a5565b2f2.PNG)
When segmentMaxFill becomes negative or zero, the 'entries' array is doubled whenever a new element is added and the size of the array rockets to be a negative value (1.073.741.824 -> -2.147.483.648) because of Integer Overflow.
Hope this helpful for you.

**Comment by cruftex** [comment]
> I'm sorry that I didn't pay much attention to heap size and cache size cause I only care where the problem comes from (your expression to calculate segmentMaxFill) and how to fix it. 

I appreciate that.

Please mind that you are reporting a problem, but its unclear in what usage scenario it happens and how severe it is. For deciding on how to proceed and for the information of other users it is helpful to give information on how to reproduce a problem.

Depending on your usage, environment and configuration the hash table sizes can look very different.

**Comment by cruftex** [comment]
> When the amount of element overtakes 2^24 and HeapCache.TUNABLE.hashLoadPercent value is default (64)

So I assume the worst case would be that the problem triggers at 2^24 * 64% = 10M entries.

**Comment by detohaz** [comment]
I'm sorry for the lack of information, but would you please clarify which cache size and heap size you need? The ones of JVM global flags or of running instance?

**Comment by cruftex** [comment]
> I'm sorry for the lack of information, but would you please clarify which cache size and heap size you need? The ones of JVM global flags or of running instance?

The actual instance sizes, when the problem hits would be interesting.

Meanwhile I produced a test and a fix. Maybe you want to check:
https://github.com/cache2k/cache2k/commit/3c9ccff12608c598c387ec50957089784cc4b618

The test does just call the hash table expand directly and does not add entries to the cache, to minimize the test runtime and footprint.

**Comment by detohaz** [comment]
The total memory of running instance at that time is around 11.4Gb, heap size 11506Mb (just for cache2k storage, and JVM MaxHeapSize is 27305Mb).
Total of element in the cache at exception time is 10.674.603.

Is it what you mean? Please correct me if I'm wrong.

**Comment by cruftex** [comment]
@detohaz: Perfect, thanks for the information!
That is really bad luck, I did test with 10 million entries and thought probably no one will have a bigger cache ;) Sorry for the inconvenience cause by this bug.

**Comment by pompeywebb** [comment]
When will the fix for this bug be released?

**Comment by cruftex** [comment]
@pompeywebb, thanks for the "ping". I just release version 1.2.2.Final to Maven central, which includes the fix.

**Comment by pompeywebb** [comment]
@cruftex many thanks!
