### ISSUE TITLE
Provide rename operation

### ISSUE THREAD

**Issue by quaff** [cache2k/cache2k#113]
I'm implementing servlet 4.0 [changeSessionId](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#changeSessionId--) , We need rename operation that doesn't change state of CacheEntry (value and expiration), like [redis rename](https://redis.io/commands/rename).
Workaround for current version is much appreciated.

**Comment by cruftex** [comment]
Hi @quaff,

is this the use case:

https://github.com/ironrhino/ironrhino/blob/master/src/org/ironrhino/core/cache/impl/Cache2kCacheManager.java

or do you use cache2k another way for the sessions?

I think the basic problem is, that there is no method in cache2k to read back the expiry time. The workaround would be to wrap the value into another object that also keeps the expiry time.

**Comment by cruftex** [comment]
Oh, another thought: `changeSessionId` is called as part of the request processing, so a TTI expiry for the session would restart any way. If the entry expiry of the cache is the same as the session expiry, there is actually no need for preserving it. So maybe some other frameworks use the redis rename functionality, but I don't see a need for it. What do you think?

**Comment by quaff** [comment]
Yes, I rewrite servlet session use CacheManager as backend store, cache2k for standalone application, redis for distributed application. session is marked dirty and write back as current `changeSessionId` implementation, it will restart TTL, but the `RedisCacheManager` is not running in the same JVM, it paying the cost of the additional bandwidth, especially large value, and redis `rename` can fix it, so I wish there is a identical operation in `Cache2kCacheManager`. It's true that `changeSessionId` should restart TTL, but I believe there is some other user case only change key and preserve the state, my suggestion is provide a `rename` method, and an overload method to accept new TTL if someone want to reset expiry.

BTW: Can I get TTL of key like redis `ttl`?
```
	@Override
	public long ttl(String key, String namespace) {
		throw new UnsupportedOperationException();
	}
```

**Comment by cruftex** [comment]
> BTW: Can I get TTL of key like redis ttl?

No, not yet. I'll see what I can do in the next version.
I opened an issue for that: https://github.com/cache2k/cache2k/issues/115

> my suggestion is provide a rename method

Since cache2k is in memory, it's not a performance issue. So for `changeSessionId()` basically:

````
cache.put(newKey, cache.peekAndRemove(oldKey));
````

Will be good enough. TTL is reset any ways.

> It's true that changeSessionId should restart TTL, but I believe there is some other user case only change key and preserve the state

I am very resistant to add extra functionality since I spend a lot of time to "clear" the interface from a lot of fuzz and make it quite concise. I am always happy to discuss possible solutions for a relevant use case, and add new functionality when I see a real need for it, so please check and let me know about the other use case.

**Comment by quaff** [comment]
```
cache.put(newKey, cache.peekAndRemove(oldKey));
cache.remove(newKey);
```
This will restart TTL with cache level default expiry, as you have peek my `Cache2kCacheManager`, actually I ignore cache level default expiry, expiry is set per key, to keep consistency with redis. If cache2k doesn't provide rename operation, I need keep TTL in mind, and TTL could be invisible in `changeSessionId` implementation, redis doesn't rely on TTL.
If cache2k provide `ttl` opration, we can read TTL from oldKey then set on newKey.

**Comment by cruftex** [comment]
You can insert the new key and set the TTL in one go:

````
cache.invoke(newKey, e -> {
    e.setValue(cache.peekAndRemove(oldKey)).setExpiryTime(System.currentTimeMillis() +  imeUnit.toMillis(timeToLive));
});
````

I'll check and see about providing the current TTL/expiry in the next version.

**Comment by cruftex** [comment]
Closing this request, since there are alternative solutions for the underlying usage scenario.
