### ISSUE TITLE
Contributor guide

### ISSUE THREAD

**Issue by cybuch** [cache2k/cache2k#119]
Hey,
have you considered adding a contributor guide? Also I've seen that many repos have some issues have marked as good first issue'. I guess that it would increase contributors count and have possitive impact on this repo.

**Comment by cruftex** [comment]
That is a good suggestion. At the moment and the next months I am doing quite heavy changes. After things settle a bit I'll write up a contributor guide.

**Comment by cruftex** [comment]
Added a contributor guide, which is at:
https://github.com/cache2k/cache2k/blob/master/CONTRIBUTING.md

Thanks for the hint.
