### ISSUE TITLE
How to configure a cache properly?/Provide more JavaDoc for CacheConfig

### ISSUE THREAD

**Issue by tburny** [cache2k/cache2k#12]
Properly configuration of a cache is vital for expected behavior  and maybe performance. However most of the methods for `CacheConfig`/`CacheBuilder` lack any explanations in JavaDoc and no other documentation regarding configuring the cache can be found.

As a newbie to caching I need a cache that expires entries if there hasn't been a `get(key)` operation for more than 30 Minutes.

    Cache<String, MyClass> cache =
      CacheBuilder.newCache(String.class, MyClass.class)
        .source(MyClass::new)
        .name(getClass())
        .expiryDuration(30, TimeUnit.MINUTES)
        .maxSize(10000)
        .backgroundRefresh(false).build();

What is the difference between `maxSize` and `maxSizeBound`?  I want to limit the cache to a maximum amount of lets say 10k. When reaching the limit, the oldest entries should be evicted from the cache.
Does `backgroundRefresh(false)` trigger the desired behavior that entries are only refreshed upon access?

Is it possible to register an event handler which is called after an entry expires and is removed from the cache?

Like a method `expiryHandler((o) -> enqueueStoringToDatabase(o))` in `CacheConfig`.

**Comment by cruftex** [comment]
Your configuration above does what you want it to do.

I will keep the issue open so I remember to update the config elements that make confusion.

**Comment by tburny** [comment]
Please also mention the default values :)

**Comment by rvansa** [comment]
Could you please describe the `maxSize`/`maxSizeBound` at least here, when it's not mentioned in JavaDoc so far?

**Comment by cruftex** [comment]
`maxSize` is the same then Infinispans' `eviction/maxEntries`:

> The maximum number of entries hold by the cache. When the maximum size is reached, by
> inserting new entries, the cache eviction algorithm will remove one or more entries
> to keep the size within the limit.

I will rename this parameter to `maxEntries` or `entryCapacity`, to be more clear. "size" is very ambiguous.

The methods `maxSizeHighBound` / `maxSizeLowBound` do nothing yet. These were intended for a feature of the cache that adapts the size by itself. I will remove these parameters.

The parameter `heapEntryCapacity` (already with the capacity wording scheme...) controls the number of entries in the heap, the rest up to `maxSize` will be stored in non-heap storage. Off-heap is experimental, so I should probably remove it at that level of configuration, too.

**Comment by cruftex** [comment]
Closing this. Constantly improving the documentation right now.
