### ISSUE TITLE
Cache ocupation not appearing on Spring Actuator

### ISSUE THREAD

**Issue by jbiason** [cache2k/cache2k#120]
I'm having an issue with using Cache2K and the Spring Integration + Spring Actuator (unfortunately, I'm not sure if it's a problem with my Spring configuration or a limitation in the current Cache2K implementation).

I've enabled Cache2K on my project using "cache2k-api", "cache2k-spring" and "cache2k-core" following the docs. Everything looks alright and things are being cached.

I've also enabled Spring Actuator. I can enable the cache monitoring over HTTP with `management.endpoints.web.exposure.include=info, health, metrics, caches". The cache names appear, and I can retrieve most of its information, but I don't see the current cache size or memory usage of the cache.

Is there something else that must be enabled for those values to be exposed?

**Comment by cruftex** [comment]
> The cache names appear, and I can retrieve most of its information, but I don't see the current cache size or memory usage of the cache.

Interesting! I did a bit of research on how that might work. Spring Boot 1 had an own cache statistics abstraction via [CacheStatisticsProvider](https://docs.spring.io/spring-boot/docs/1.5.21.RELEASE/api/org/springframework/boot/actuate/cache/CacheStatisticsProvider.html). Spring 2 seems to have dropped that, in favor of micro meter integration which support generic cache metrics, https://micrometer.io/docs/ref/cache.

I think for convenience, good OOTB experience and generic tooling support we should support micro meter within cache2k. It should not be very difficult. Just opened #121.

Your current options are to use JMX, check the [User guide](https://cache2k.org/docs/latest/user-guide.html#jmx-metrics) on how to enable it. There is also a HTTP to JMX in Spring, take a look at: [Spring reference - Monitoring and Management over JMX](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-jmx.html)

Another option is to use the cache via the JCache API. Micro meter supports the JCache statistics directly. So then everything will show up.

Of course you can do both. Then you get the basic statistics via Actuator, advanced JCache statistics via JMX and even more detailed cache2k statistics via JMX.

Keeping the issue open, in case you have further questions. It is worth to add some hints in the documentation as well in the Spring chapter.

**Comment by jbiason** [comment]
Ok, kinda like a weird issue (due the way we work here): We prefer to enable features programmatically or using a single YAML file (`application.yml`); the docs only mention `cache2k.xml` and `Cache2kBuilder`, none of which we use (again, a single YAML file and, for the code, we are using `SpringCache2kCacheManager`, which doesn't have any JMX properties -- or something that I can easily spot that would give me access to the builder).

Is there anything that, using Spring, we can get access to enable JMX reporting?

**Comment by cruftex** [comment]
You can enable it programmatically, as documented here:
https://cache2k.org/docs/latest/user-guide.html#programmatic-setup

Here an example how to enable JMX for all Spring caches:

````
  @Bean
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager()
      .defaultSetup(b->b.enableJmx(true))
  }
````

**Comment by jbiason** [comment]
Awesome, that did the trick. I can pick the cache statistics over JMX using JConsole now.

But back to the original question, even through JMX, I can't find the real occupation of the cache:

![Screenshot from 2019-07-30 11-24-44](https://user-images.githubusercontent.com/228850/62137640-a8f90a80-b2bc-11e9-93a3-21066c3b7119.png)

This value is good for us so we can properly size our caches and not overload our deployment by using larger than necessary containers.

**Comment by cruftex** [comment]
@jbiason Since the list looks alphabetically sorted, I assume you need to scroll down just a little to an attribute called "Size". :)

**Comment by cruftex** [comment]
BTW: A bit more detailed description on the attributes is in the Java Doc for the api package, see:
https://cache2k.org/docs/latest/apidocs/cache2k-api/org/cache2k/jmx/CacheInfoMXBean.html

**Comment by jbiason** [comment]
I swear I didn't see the scrollbar :fearful:

**Comment by cruftex** [comment]
Haha, I did :)

**Comment by jbiason** [comment]
Alright, since it was mostly some missing some configurations (and me in need of new glasses to see scrollbars) and there is nothing wrong with Cache2K, I'm closing this issue.

Thanks for the help, guys.

**Comment by cruftex** [comment]
You are welcome. BTW: I did experiments on direct Spring Actuator support meanwhile. I will include that in the next version. You might want to monitor #121. If you have any other questions, just shoot ;)
