### ISSUE TITLE
Usage Guideline / Feature Recommendation  -- 'One Object Cache' or 'All Map Loader'

### ISSUE THREAD

**Issue by DALDEI** [cache2k/cache2k#122]
A common use case I have is one that would be addressed by a bulk loader like #116 .
An alternative approach could be a 'One Object' cache which could store a single object (which could be a map).

An example of this is caching values from an API that only have entry points to return all values,
or that the API to return all values is more efficient then iterating over all values.
In many use cases -- where the size of the return set is small - say 100 values each < 100 bytes -
the cost of 1 API call returning all values can be about the same as 1 call for 1 value.
Given internet latency even a very quick API might take seconds to get all values 1 by one but subsecond to get them all in 1 (or a few of paginated ).
Particularly painful is if there is ONLY an api for the 'get all' case -- in that case using a  read-through cache is worse then pointless.  F

Another case -- which can be considered a derived case -- is where 'One' object (which may be complex) benefits from all the other non-map-like  features of cache2k  -- e.g. expiration, read through caching, resilliance, cache stampede etc. 

One could make a single cache of Name -> Object to handle all of these, but they would all have to have the same cache characteristics and making the universal loader is a PITA. (would have to build an indirectly layer to map name -> real loader).
One could make a "Cache with a single entry" -- which may be the best solution but 'seems an odd fit' to the interface, particularly if you don't know the internals enough to judge if behaviour is affected by always having a single 'hot spot'  -- a typical 'bad design' for caching .

Suggest either/or some comments/documentation/implementation to address this question.
One such might be a 'blessed' API exposing the 'One Object Cache' which could be as simple as a derived class that hard-codes a single key to the map making the get() and set() not take parameters.   IMHO this is useful to users as they could expect that the author had thought through the details and may decide to optimize / test for this use case over time.

An interesting extrapolation could be that a derived One Object' cache uses a Map as its "One Object".
This would nearly complete the 'bulk load all' concept -- 
The missing bits I think would be to trap the 'set' calls to the map to propogate down to trigger whatever cache2k is doing when you write to a cache (how it affects expiry for example) otherwise 
all accesses would appear to be 'read' accesses.

**Comment by cruftex** [comment]
> An alternative approach could be a 'One Object' cache which could store a single object (which could be a map).

There is the concept of a Memoizer. The term was coined by the Java Concurrency in Practice book. A memoizer is included in Guava or Apache Commons. Example: 

````
private final Supplier<Integer> value = Suppliers.memoize(new Supplier<Integer>() { 
  public Integer get() {
    return 123;
  };
});
````

Of course, this is not a cache and lacks the additional features.

I thought about such a feature by my self a couple of times, so thanks David, to bring this up. The reasons why its not there:

- It is quite seldom in our code. Sometimes we started to just store one object, but found out that separating it was more efficient, so its a normal cache again. Quite often it is the use locale. So instead of just storing the "raw data" we already precomputed values, depending on the contextual usage in the application and cached this.
- I didn't come up with a good API idea

> The missing bits I think would be to trap the 'set' calls to the map to propogate down to trigger whatever cache2k is doing when you write to a cache (how it affects expiry for example) otherwise
all accesses would appear to be 'read' accesses.

No. As soon as values expire individually, you will need to update them individually. Then its a normal cache again. You can get it as a map via, `asMap()`. In this case implementing the bulk loader and some auto warm up feature would be a good improvement direction.

> Suggest either/or some comments/documentation/implementation to address this question.

Yes. This issue is a good start ;)

My basic recommendation would be to define a separate key class as a marker for those caches. What about:

````
public final class MemoizerKey {
  public static MemoizerKey INSTANCE = new MemoizerKey();
  private MemoizerKey() {}
}
````

From a properly typed cache, you can retrieve the single value only via cache.get(MemoizerKey.INSTANCE).

**Comment by DALDEI** [comment]
Ill be specific about the case set Im referring.  This behaves  differently then you describe e.g "No. As soon as values expire individually, you will need to update them individually. Then its a normal cache again." 
THe APIs do *NOT* have this feature, they are only 'list' apis and the thigs listed do not have external ID's such that one could fetch them one off.   You would not know what to fetch anyway if you didn't have the ID to start with, but evenif you do these cases either do not have or have no benefit in using as "Get 1" vs "get ALL'
So the only way I can think of is to treat the 'list' as the 'cached object'
Now depending on the list kind, there may be one or there may be many.

The cases Im refering to are exemplifed by AWS resource API calls,  but there are parallels on other domains.

Examples: These are all calls that return a LIST but that have no method for identifying or returngin "1"  
The list is either global (well, per account or per region, seperate cache entries if your app is mutli-account )   Or per parent item.  (which can be recursive wrt the parent itself being part of a larger list, or can be 1 off queries)

"Get Execution History Events for a Step Function" :   List result ONLY, key is step function id
"Get Executions for a Step function:"   List result ONLY, key is step function id
"List S3 Objects"   -->  List result only,  optional key is path prefix 
"Get Metrics For XXX"  ->  List result only, key(s) are dimensions and metric names and time ranges

More 'traditional'. analogs
Filesytem List Directory   -> list result only, key is parent (or root of tree)
Get Lines from File   -> list result only
Get list of users 
Get list of classes in package
Get list of emails in inbox


The 'key' to the distinction between a 'list of' and 'a single of'  , and why they are not interchanable usually , is that list API's tend to return a subset of the 'get single of' API -- e.g. maybe only a name, or a name+id+very-little-metata.   So generlaly the entry from a 'list of xxxx' can not be used in place of an entry for 'Get a Single Of'  -- not the same data.

Another 'key' is the private nature of keys -- when an app needs a 'list of' its often because it doesnt know upfront what there is and there no way to ask for 1 thing by generalty   Example
"I want a file(s) with the extension .META in a directory IF it exists"
"I want ALL .META files in a directory tree IF they exist"
"I want all log entries since XXXXXX"
"I want all log entries BEFORE XXXXXX"
Its a context dependant decision to determine the optimal expiration policy -- you need to know upfront the behaviour of the system and wheter certian things are possible or if you care about them. 
Example:  "Get history events of execution"  will continue to return *new events* on each call along with the old ones,   UP until the step function is completed or failed then it will return the exact same list forever.
( working on a cache ExpirePolicy right now to encode this domain knowlege)

CloudWatch metric events and logs are interesting -- only LISTs are returned, each entry does not have identity (in a usable way).  Depending on the parameters the resulting list may be idempotent or may be changing.  Examplek, querying for events in the past will (almost always)) return the same results but change the request parameter to include current events and the results will change.

What Im debating (myself) with is where is the best role for an in-memory cache vs a distributed cache (like Redis or memcached) -- for small apps and clusters -- where there is not likely to be much sharing of data.   Is a distributed cache of more values if only one client uses it ?
Can an in-memory cache gain some of the attributes of a distributed cache (persistance, external APIs for tool use ),  is a in-memory cache usefule or just painful when in front of a persistent cache.
Can 'advanced' distributed cache APIs be integrated well with in-memory cache APIs to provide a inelligent 'face' to the whole caching thing ?
( ex:  redis API reddison has java binding that allow a java object like a Map to actually be the interface to a distributed cache concurrently by multiple clients)
Where should the cache live in a micro-service architecture ?
and to end at the beginning

What is a good way to cache API calls in general ?
https://www.balisage.net/Proceedings/vol19/print/Lee01/BalisageVol19-Lee01.html  --> in part a discussion of caching REST APIs

**Comment by cruftex** [comment]
Thanks for your ideas. I think the latter questions could be more valid in Stackoverflow questions or maybe some discussions groups (which one?). I'd be happy to discuss more on that, however, I think this (single) issue is the wrong format.

I keep this issue for the "One Object Cache" aspect. Maybe others have ideas as well. Once ideas converge I would add something to the cache2k API and/or documentation.

**Comment by cruftex** [comment]
Closing this, but will keep ideas in mind. Needs to be split up in actionable issues.
