### ISSUE TITLE
Non-null / Nullable annotations (Improve Kotlin support)

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#125]
Some languages, compilers, checking frameworks are more strict about null.
E.g. `Cache2kBuilder.build()` never returns null. Since this is not specified, IntelliJ producing a warning.

Actually I did remove those annotations years ago, since there is no common standard for it and I don't want to have additional dependencies.

What is the recommend way now?
Can we add this in 1.x with 1.6 compatibility or wait for 2.0?

**Comment by dashfwd** [comment]
Kotlin allows the use of any of a variety of annotations, see https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations.  Any of those varieties will be remove the compiler warnings.

**Comment by cruftex** [comment]
Guava discussion about which annotations to use:

https://github.com/google/guava/issues/2960

**Comment by cruftex** [comment]
https://medium.com/dont-code-me-on-that/use-java-nullability-annotations-to-facilitate-conversion-to-kotlin-7196f0cee9e9

**Comment by cruftex** [comment]
To do this meaningful we probably should introduce new interfaces for a Cache that may hold null values.
Alternatively drop support for null values or move to Optional.

Most of the time null values are not allowed, meaning `permitNullValues(true)` is not specified. Since we have the option,
we would need to annotate the value parameters with `@Nullable`. E.g. `Cache.put(K key, @Nullable V value)`.
Since using non-null values is the common case this would reduce the usefulness of the annotations.

To do this nicely, we would need to double every cache interface and have a Nullable variant. Probably like this:

````
interface NullableCache {
  @Nullable V get(K key);
  void put(K key, @Nullable V value);
}
interface Cache extends NullableCache {
  void put(K key, V value);
}
````

The other way around would be better, so we have the complete set of methods on the Cache interface:

````
interface Cache {
  @Nullable V get(K key);
  void put(K key, V value);
}
interface NullableCache extends Cache {
  void put(K key, @Nullable V value);
}
````

**Comment by cruftex** [comment]
That's all getting quite complicated. Pragmatic approach:

All interfaces are annotated in the expectation that a value is non null.
Use cases that want to work with null can do so, but may require to suppress warnings.

**Comment by cruftex** [comment]
Update:

- Using checkerframework `@NonNull` and `@Nullable`, which Kotlin understands as well
- Not annotating `@NonNull` / `@Nullable` on every parameter and return value, instead using JSR305 to established defaults that are picked up by Kotlin. BTW: Caffeine is annotating everywhere, bu cache2k has much more methods. Its better to use defaults/conventions
- Unfortunately Kotlin is not honoring the upper type bound (as in `Cache<@NonNull K, @NonNull V>` correctly and falling back to platform types when collections are involved e.g. `Map<V, K> getAll(....)` will lead to a `Map<Int!, Int!>`.
- To establish a common contract for `<K, V>` a new interface `DataAware<K, V>` is introduced that all interfaces with `<K, V>` should extend.

**Comment by cruftex** [comment]
During my experiments I found issues in the checker framework and Kotlin:
https://youtrack.jetbrains.com/issue/KT-43262
https://stackoverflow.com/questions/64763320/problem-checker-framework-null-checker-and-lambda

**Comment by cruftex** [comment]
Delivered and released as preview: https://github.com/cache2k/cache2k/releases/tag/v1.9.2.Alpha

**Comment by cruftex** [comment]
Changing to JSR305 again and use local aliases in `org.cache2k.annotation`. Reason: If someone implements a customization with a `@Nullable` annotation (e.g. `AdvancedCacheLoader`) the annotation will be in the suggested implementation by the IDE.
We don't want to add the annotation jar as dependency, but we don't want to produce missing dependencies in client code either. This way we can have both.

Unfortunately we loose the possibility to run check with CheckerFramework.

Hopefully there will be a better solution in the future.
