### ISSUE TITLE
`javax.naming.NameNotFoundException` thrown at application startup

### ISSUE THREAD

**Issue by luciano-fiandesio** [cache2k/cache2k#130]
When creating a cache via `Cache2kBuilder`, the `Cache2kCoreProviderImpl` tries to register `org.cache2k.CacheManager.defaultName` through JNDI and it fails with `javax.naming.NameNotFoundException: Name [org.cache2k.CacheManager.defaultName] is not bound in this Context. Unable to find [org.cache2k.CacheManager.defaultName].`

The application is running within Tomcat.
The application starts up without issues, but I would like to avoid having a stack trace at start time. Is there a way to disable this behaviour?

**Comment by cruftex** [comment]
The purpose of the JNDI property is to set a different cache manager name, in case you run multiple applications with cache2k within one tomcat instance.

When nothing is set, this should be ignored. Seems like you found a bug. Sorry for that. Will correct that ASAP.

**Comment by cruftex** [comment]
@luciano-fiandesio It looks like I have introduced that problem in version 1.2.3. Version 1.2.2 will just log an error about the missing variable, but continue. Maybe you can check that?

**Comment by cruftex** [comment]
> The application starts up without issues, but I would like to avoid having a stack trace at start time. Is there a way to disable this behaviour?

You could simply set the JNDI property `org.cache2k.CacheManager.defaultName` to `default`.

I will do an update, so this gets silently ignored. Maybe I drop JNDI in the futures, since I think not many are using this.

**Comment by luciano-fiandesio** [comment]
Ok, thanks. Yeah, I think you can simply catch `javax.naming.NameNotFoundException` in `JndiDefaultNameProvider.registerCache2kExtension` and ignore

**Comment by cruftex** [comment]
Trying to release but unfortunately, I am getting timeouts from Sonatype for the Maven central upload at the moment.

**Comment by cruftex** [comment]
Verison 1.2.4.Final is released now with this fix.

**Comment by luciano-fiandesio** [comment]
> Verison 1.2.4.Final is released now with this fix.

Excellent, thanks for the crazy fast response
