### ISSUE TITLE
Version 2.0 Planing and Goals

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#133]
The versions of 2.0 pre releases will be: 1.9.x.Alpha and 1.9.x.Beta.

## Goals

- API should be 99% compatible to allow smooth transition of applications
- Minimum Java version for running: Java 8 (Now its 1.6)
- Minimum Java version for compilation: Java 8
- Remove things that were deprecated during 1.x
- Introduce new `CacheLoader` and `CacheWriter`, currently these are abstract classes
- Modularization/Jigsaw support
- Keep code base of 2.0 and 1.x mostly identical to allow a fast transition without new features or bugs holding up the release

## Non-Goals

- No new features for 2.0. We introduce new features in >= 2.2. 
- No major internal code cleanup / adaption to Java 8, we do that in >= 2.2

**Comment by vladp** [comment]
With regards to minimum java version.  
Would the goal of 2.0 be still compatible with Android SDKs below 24? 
(this is not particular important to me specifically, but just wanted to check)

https://developer.android.com/studio/write/java8-support#supported_features

**Comment by cruftex** [comment]
@vladp:

> Would the goal of 2.0 be still compatible with Android SDKs below 24?

No. It's gonna be >= 24

**Comment by cruftex** [comment]
2.0 is almost completed. So closing this.
