### ISSUE TITLE
Remove ExceptionPropagator

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#138]
cache2k has a build-in support for exceptions. Exceptions that cannot be suppressed get propagated. There is is a `ExceptionPropagator` interface to configure the behavior.

Plan:
Remove the configurable exception propagator and introduce one consistent semantic of exception propagation.

Applications can always to a `try ... catch` to wrap exceptions and augment behavior in presence of an exception.

**Comment by cr-orilibhaber** [comment]
I admit I find this feature useful and would hate to see it go.
Given this option allows me to to avoid spreading around boilerplate code for exception management by guaranteeing that the cache instance only throws a set of predefined business domain exceptions.
Furthermore, is allows me to reach out to say, a metric manager and have the cache thread do the reporting as a single unit of work.
It's convenient and flexible to provide this during cache building.

**Comment by cruftex** [comment]
@cr-orilibhaber Thanks for the feedback!

My motivation is that I don't want to pass on the `ExceptionPropagator` to a `CacheEntry`.
I have an alternative idea and probably make the propagator in use part of the `ExceptionInformation`.

**Comment by cruftex** [comment]
@cr-orilibhaber Keeping the `ExceptionPropagator` and finding a better internal solution for this.
-> won't fix
