### ISSUE TITLE
AsyncCacheLoader / Push Cache entry when fully loaded

### ISSUE THREAD

**Issue by Chasewhip8** [cache2k/cache2k#140]
Is there a way to have a completable future in the cache loader that then when completed pushes the object to the cache?

**Comment by Chasewhip8** [comment]
Kinda something like [this](https://github.com/cache2k/cache2k/issues/97)

**Comment by cruftex** [comment]
Sorry for the late response. The whole world situation has kept me busy with other stuff.

The next version will get an `AsyncCacheLoader`, it is already in git:
https://github.com/cache2k/cache2k/blob/master/cache2k-api/src/main/java/org/cache2k/integration/AsyncCacheLoader.java

There is the problem that cache2k is still Java 1.6 compatible and no Java 8 yet. Meaning no `CompletableFuture` :(
I plan to release the current state soon and then start working on cache2k 2.0 with Java 8 support.

**Comment by Chasewhip8** [comment]
I've had to do some wacky completable future nonsense to get around not having a proper implementation of this but it's great to see you working on it! I don't see a point in supporting java 1.6 anymore since 11 is becoming the gold standard now days aside from the existing 1.8.

**Comment by cruftex** [comment]
@Chasewhip8 pre-released what I have as 1.3.2.Alpha. I did some experiment with it in a servlet environment. E.g. see:
https://github.com/sensepitch/badges/blob/master/src/main/java/com/headissue/badges/GitHubStatisticsJava11Source.java

The cache itself misses still a complete async API to retrieve from it. Right now,  `Cache.loadAll` and `Cache.reloadAll` can be used for that.

Depending on your application you could actually just construct a cache that keeps completable futures: `Cache<K, CompletableFuture<V>>

**Comment by Chasewhip8** [comment]
For right now I have a solution in place but a proper async api would be awesome nevertheless.

**Comment by cruftex** [comment]
@Chasewhip8 closing this ticket as dup of https://github.com/cache2k/cache2k/issues/93 please monitor and comment this one.
