### ISSUE TITLE
Android support in version 2

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#143]
Version 2 uses Java 8 or later, so it might potentially break Android compatibility.
At the moment we don't have capacity to come up with proper compatibility testing.
While we want to avoid breaking Android compatibility, we cannot guarantee it without proper testing in place.

What would be needed:
- static verification that only APIs present in Android are used
- CI jobs that runs test suite

**Comment by Betalord** [comment]
Any news on this front? I'd really like to use cache2k on Android, but it seems it's not working.

**Comment by cruftex** [comment]
@Betalord: We switched to Java 8 with version 2, however, there weren't any major changes which should break Android compatibility in general. It's just untested. If you find a problem with Android and cache2k version 2.x, please file an issue.

**Comment by Betalord** [comment]
@cruftex I'm having problems running it on Android. I add cache2k-api-2.0.0.Final.jar and cache2k-core-2.0.0.Final.jar under Java Build Path -> Libraries, however I get following error:

```
E/AndroidRuntime(31883): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/cache2k/Cache;
E/AndroidRuntime(15126): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.cache2k.Cache" on path: DexPathList[[zip file "/data/app/com.betalord.sgx-izdkQ73Yn9b5nS5voTUTJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.betalord.sgx-izdkQ73Yn9b5nS5voTUTJA==/lib/arm64, /data/app/com.betalord.sgx-izdkQ73Yn9b5nS5voTUTJA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
```

**Comment by cruftex** [comment]
@Betalord: More information to reproduce the problem would be helpful (IDE, API level, build tools, etc.). However, it seems that you don't bundle the jars with your application and just have it in the path during compile time.

**Comment by Betalord** [comment]
I'm using Eclipse 4.3 (Kepler), API 28, JRE 8 (with compiler compliance level 1.7), Libgdx 1.9.9. ... not sure what else? Anyway, if I tick the two JARs under "Order and export" (which I do for all JARs I use) and clean all my projects, then I get this error:

> Conversion to Dalvik format failed with error 1

Note that Cache works perfectly well on desktop (I have my app divided into 3 projects: android, desktop and core).

**Comment by cruftex** [comment]
For testing the 1.x versions of cache2k I had test projects building a small Android app and also testing the proguard rules. These can be found here:
https://github.com/cache2k/cache2k/tree/service-1.4/test-android
https://github.com/cache2k/cache2k/tree/service-1.4/test-android-proguard

TravisCI and CircleCI have the option to do CI builds for Android apps. I think for the needed setup Open Source Andrioid apps could be used as an example.

In the long run I want to move all core tests into the cache2k-testsuite. Ideally we package and run this suite on Android as well.

**Comment by cruftex** [comment]
@Betalord 
I just installed the latest Android studio (2020.3.1) and did a quick test with 2.0.0.Final and 2.5.1.Alpha. Could not find a general problem, meaning, a simple test with building the cache and doing a put and get works.

Minimum API level is 26, since `java.time.Duration` is needed an probably other stuff.

**Comment by cruftex** [comment]
Next steps
have a CI job that runs the latest commit and its tests in an Android simulator.
I already put some parts of the test suite separately in the `cache2k-testsuite` module.
Ideally the testing harness should support Junit5 since I plan to move all tests from 4 to 5.
