### ISSUE TITLE
Exception uses as flow control

### ISSUE THREAD

**Issue by fbacchella** [cache2k/cache2k#170]
I’m using cache2k 2.0.0.Final.

In org.cache2k.processor.EntryProcessor, I see the code:
```
        try {
          R result = processor.process(mutableEntry);
          c.result(result);
        } catch (WantsDataRestartException rs) {
          c.wantData();
          return;
        } catch (NeedsLockRestartException ex) {
          needsLock = true;
          c.wantData();
          return;
        } catch (Throwable t) {
          c.failure(new EntryProcessingException(t));
          return;
        }
```

So it's code were exception are used as flow control. But it's usually a bad idea, see https://shipilev.net/blog/2014/exceptional-performance/ for a deep analysis of that.

For example, when generating flamegraph for some of my code, I get the following result:

![flamegraph](https://user-images.githubusercontent.com/967097/105698399-1f081d00-5f06-11eb-8592-2bda28f89f08.png)

Most of the time is spent filling in the stack trace.

The code that generate this stack can be found at [NettyNameResolver.java](https://github.com/fbacchella/LogHub/blob/master/src/main/java/loghub/processors/NettyNameResolver.java)

Performance could be increased I think if both WantsDataRestartException and NeedsLockRestartException (and perhaps other) were static and not saving the stack.

This constructor can be used for that:
```
protected Exception(String message,
                    Throwable cause,
                    boolean enableSuppression,
                    boolean writableStackTrace)
```

If writableStackTrace is set to false, the stack trace is not saved.

**Comment by cruftex** [comment]
@fbacchella thanks for the analysis. That looks like a quick win. I will put an improvement in the next release.

I also looked at your code. Using JCache you need to do per entry TTL by yourself. Cache2k would support this directly and do an efficient expiry via timer wheel and scheduler.

**Comment by cruftex** [comment]
I implemented your suggestion and released an alpha update for verification. Thanks for reporting!
https://github.com/cache2k/cache2k/releases/tag/v2.1.2.Alpha
