### ISSUE TITLE
Improve CoalescingBulkCacheLoader

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#173]
The `CoalescingBulkCacheLoader` is delaying requests and trying to combine many requests into one bigger bulk request during the delay time. The idea is to optimize loading and better utilize the bulk loader introduced in version 2.2.

Depending on the application this might have negative impact on the response time, e.g. when an application is doing multiple independent sequential cache requests for one user request. For example: a request to a product page may read the product data, product text depending on the user language, price information, availability information, supplier information, leading to 5 independent cached database requests.

An obvious improvement could be to enable the coalescing and therefore the delay only for load requests caused by refresh ahead.

This issue should collect some more feedback and ideas.

**Comment by cybuch** [comment]
>An obvious improvement could be to enable the coalescing and therefore the delay only for load requests caused by refresh ahead.

That's exactly what I did in my own implementation and that's how I expect it work. 

So whenever I need the data (when it's not cached ye) then I get right away, but I'll willingly wait for data refresh to make sure that's optimized.

**Comment by cruftex** [comment]
@cybuch thanks for the input. So I am making this change now, otherwise its of limited use.
