### ISSUE TITLE
Variable cache expiry

### ISSUE THREAD

**Issue by luciano-fiandesio** [cache2k/cache2k#176]
from the cache2K documentation:

> Each entry may have a different expiry time. This can be achieved by specifying an ExpiryPolicy. The ExpiryPolicy calculates a point in time, when a value expires. The configuration parameter expireAfterWrite is used as a maximum value.

I couldn't find any example to set a variable expiration time and the `Cache` API only has a `put` method which does not allow to specify any ExpiryPolicy.

I could only find this very old Stackoverlfow answer: https://stackoverflow.com/a/47096840

Any pointer?

Edit: I noticed now that there is an `expireAt` method on the `Cache` interface.

**Comment by cruftex** [comment]
Hmm, actually it should be described here:
https://cache2k.org/docs/latest/user-guide.html#expiry-and-refresh

But there is no example. To start with, the simplest example would be:

````
    Cache<Key, Data> cache = new Cache2kBuilder<Key, Data>() {}
      // maybe a loader for read through
      .loader(k -> new Data())
      .expiryPolicy((key, value, now, currentEntry) -> now + value.getMaxAgeMillis())
      .build();
````

See how the expiry policy calculates the expiry from the value. If you you use `Cache.put` `now` is the time when you call put, with a loader `now` is the time before the load started.

**Comment by cruftex** [comment]
If you don't operate in read through or if the expiry time does not derive from the value, you can set it via `Cache.expireAt(key, time)`. Or to put and set an expiry time atomically as in the Stackoverflow comment:

```
  cache.invoke("key", e -> e.setValue("value").setExpiry(e.getStartTime() + TimeUnit.MINUTES.toMillis(120)));`
````

**Comment by luciano-fiandesio** [comment]
Awesome, thanks!

**Comment by cruftex** [comment]
More variations:

- You can calculate different expiry based on the previous cache entry. E.g. lowering the refresh duration when there is a lot change in the data
- You can implement the interface `ValueWithExpiryTime` on the cached value. That adds an expiry policy automatically
- You can return a negative time value in case the expiry should be exact to the millisecond w.r.t. to `System.currentTimeMillis()`. However better use `Expiry.toSharpTime()` to make it more speaking whats going on

**Comment by cruftex** [comment]
Keeping the issue open for the moment in case you have follow up questions and then I would extend the user guide accordingly.

**Comment by cruftex** [comment]
I started to write down example scenarios for the expiry policy as test cases. This ongoing. Here is the first version:
https://github.com/cache2k/cache2k/blob/8918069999fb1df416e7a72a44f3658403d69517/cache2k-core/src/test/java/org/cache2k/test/example/ExpiryPolicyExampleTest.java

**Comment by cruftex** [comment]
Latest example is now here:
https://github.com/cache2k/cache2k/blob/master/cache2k-testsuite/src/main/java/org/cache2k/testsuite/example/ExpiryPolicyExampleTest.java

Also extended the documentation.
