### ISSUE TITLE
Spring Cache integration

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#18]
Probably simple once JSR107 is in place.

**Comment by jirutka** [comment]
I look forward to Spring Cache integration.

**Comment by cruftex** [comment]
Yep, more people seam to like this happening:
http://stackoverflow.com/questions/34946709/how-to-integrate-cache2k-caching-with-spring-mvc-4-2-4

Right now I prioritize on stabilizing cache2k and work towards a 1.0 release, I cannot work on more integrations simulataously. If somebody wants to do something I'll support this as best as I can.

@jirutka maybe this could be a students project?

**Comment by tburny** [comment]
I tried to explore this a bit and came up with this SSCE in Kotlin: https://github.com/tburny/cache2k-spring

What I tried:
- Create a Spring CacheManager based implementation
- Use Spring's `@Cachable` annotation
- Picking up any preconfigured caches and using them via their name
- Allow specifying the class loader (default: Springs Bean ClassLoader) and a name for `CacheManager`

Did not try (yet):
- Simply wiring Cache2k <-> JSR-107 <-> Spring without any fancy stuff
- Layering of cache implementations (you can totally do that in Spring)
- Further Cache configuration mechanisms
- Auto-Discovery of cache implementation

My experience so far is that cache2k and Spring caching are somewhat orthogonal to each other:  cache2k offers nice declarative configuration, explicit cache sources and good type safety. Caching in Spring is seen as a somewhat cross-cutting concern solved via Aspect Oriented Programming(AOP). As a result caches in Spring are untyped and their cache loader logic is implicitly generated by Spring AOP.

Note: I'm not a Spring expert :)

**Comment by cruftex** [comment]
I just finalized the Spring support, which can be found here:
https://github.com/cache2k/cache2k/tree/master/cache2k-spring/src/main/java/org/cache2k/extra/spring

Tests with a tiny test project with Spring 5 and Spring Boot look good.
Next step will be to write some documentation and do a pre-release in 1.1.2.Alpha.

@snicoll any comments?

**Comment by cruftex** [comment]
Version 1.1.2.Alpha just got released with Spring integration.

Documentation: https://cache2k.org/docs/latest/user-guide.html#spring

**Comment by cruftex** [comment]
Meanwhile I checked the exception handling and simplified the code. 

I would like to change the name of the manager from `Cache2kManager` to `SpringCache2kManager`. Since this is within the cache2k code base, there needs to be an easy differentiation between the many caches and managers. This way we avoid a name clash for people importing `org.cache2k.*` in case I introduce a `Cache2kManager` at some point.

**Comment by cruftex** [comment]
Another minor update on the Spring Framework support just released with 1.1.3.Alpha.
