### ISSUE TITLE
Missing @Nullable annotations in AbstractCache

### ISSUE THREAD

**Issue by dsvoronin** [cache2k/cache2k#192]
Hello, Jens!
I believe `AbstractCache` missing some `@Nullable` annotations. Like here:

https://github.com/cache2k/cache2k/blob/f681da1dd12a334279b06ca32448c0aa680ab101/cache2k-api/src/main/java/org/cache2k/AbstractCache.java#L57-L60

While `Cache` interface has it: 

https://github.com/cache2k/cache2k/blob/f681da1dd12a334279b06ca32448c0aa680ab101/cache2k-api/src/main/java/org/cache2k/Cache.java#L200

I think i can find some more on other methods.

It is blocking me to write simple stub, extending `AbstractCache` in Kotlin, because it's a little bit more strict regarding nulls.

Implementing `Cache` interface in Kotlin has some other problems with `invoke` and `invokeAll` signature, i will try to investigate it later

Am i right on my assumptions?
If yes, let me know and I'll do a PR on this.

Thanks for great library!

**Comment by cruftex** [comment]
Good point, Dmitriy! I put it in `FowardingCache` also. I am happy for a PR.
