### ISSUE TITLE
please let SpringCache2kCacheManager#defaultSetup know which cache to build

### ISSUE THREAD

**Issue by trydofor** [cache2k/cache2k#200]
please pass the cash name `n` to `defaultSetup` in `Line 121`
something like `defaultSetup.apply(getDefaultBuilder().name(n)).name(n)` is ok.

because some cache spec depens on name, so builder need the name (`builder.config().getName()`) to build cache

https://github.com/cache2k/cache2k/blob/0eaa156bdecd617b2aa4c745d0f8844a32609697/cache2k-spring/src/main/java/org/cache2k/extra/spring/SpringCache2kCacheManager.java#L115-L123

**Comment by trydofor** [comment]
or change buildAndWrap to `protected` to be `override`

https://github.com/cache2k/cache2k/blob/0eaa156bdecd617b2aa4c745d0f8844a32609697/cache2k-spring/src/main/java/org/cache2k/extra/spring/SpringCache2kCacheManager.java#L282

**Comment by cruftex** [comment]
Thanks for the ideas! I don't understand clearly at the moment which problem you are trying to solve. Can you please describe better what you want to do maybe with examples? How many caches do you want to setup with what configuration?

**Comment by trydofor** [comment]
BTW, it would be better to change the return type of `getCache(String name)` from `SpringCache2kCache` to `org.springframework.cache.Cache` as super. 

because in my case, i want to use some delegated Cache to deal with `null` both in Cache2k and Redis. for now, the delegated class must extend `SpringCache2kCache`.

**Comment by cruftex** [comment]
@trydofor: Regarding the last comment:
I didn't have extension in mind `SpringCache2kCacheManager` with the design of it. Maybe the cleaner approach would be to wrap it. The `CacheManager` interface has only two methods.

**Comment by cruftex** [comment]
@trydofor: Here is an example how you can add dynamic configuration.

````
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager()
      .defaultSetup(builder-> {
          builder.config().getFeatures().add(new Feature() {
            @Override
            public <K, V> void enlist(CacheBuildContext<K, V> ctx) {
              if (ctx.getName().endsWith("-long")) {
                ctx.getConfig().builder().expireAfterWrite(88, TimeUnit.MINUTES);
              }
            }
          });
          return builder;
        });
  }
````

The method `enlist` runs just before the cache is created and after all the other configuration code. So you can augment configuration values and also you have already access to some infrastructure, like executors and the timing reference.

The `Feature` class is actually meant to construct cache extensions which would coordinate several cache configuration parameters and customizations (like the loader and expirypolicy). I give a full blown example in the next comment.

**Comment by cruftex** [comment]
Alternatively you can also add a configuration and builder object, here is an example:

````
  public class TtlOptions extends ToggleFeature implements WithSection<TtlOptionsConfig, TtlOptionsConfig.Builder> {

    @Override
    public <K, V> void doEnlist(CacheBuildContext<K, V> ctx) {
      TtlOptionsConfig cfg = ctx.getConfig().getSections().getSection(TtlOptionsConfig.class);
      if (ctx.getName().endsWith("-max")) {
        ctx.getConfig().builder().expireAfterWrite(cfg.getLongTtl());
      }
      if (ctx.getName().endsWith("-min")) {
        ctx.getConfig().builder().expireAfterWrite(cfg.getShortTtl());
      }
    }

    @Override
    public Class<TtlOptionsConfig> getConfigClass() {
      return TtlOptionsConfig.class;
    }
  }

  public class TtlOptionsConfig implements ConfigSection<TtlOptionsConfig, TtlOptionsConfig.Builder> {

    private Duration longTtl;
    private Duration shortTtl;

    public Duration getLongTtl() { return longTtl; }
    public void setLongTtl(Duration v) { this.longTtl = v; }
    public Duration getShortTtl() { return shortTtl; }
    public void setShortTtl(Duration v) { this.shortTtl = v; }

    public Builder builder() { return new Builder(this); }

    public static class Builder implements SectionBuilder<Builder, TtlOptionsConfig> {

      TtlOptionsConfig config;

      public Builder(TtlOptionsConfig config) { this.config = config; }

      @Override
      public TtlOptionsConfig config() { return config; }

      public Builder longTtl(Duration v) { config.setLongTtl(v); return this; }
      public Builder shortTtl(Duration v) { config.setShortTtl(v); return this; }
    }
  }
````

With that in place, the actual configuration code looks more crispy again:

````
  public CacheManager cacheManager() {
    return new SpringCache2kCacheManager()
      .defaultSetup(b ->
        b.enableWith(TtlOptions.class, ttl -> ttl
            .longTtl(Duration.ofMinutes(10))
            .shortTtl(Duration.ofMinutes(1))));
  }
````

All configuration is now bean compatible and storing it in an external XML is possible, too. You can reuse the cache setup scheme in different projects. If the your dynamic setup code gets quite long, this might also be clearer. If its only short, maybe the first approach is easier and better for now, since less code.

**Comment by trydofor** [comment]
@cruftex thanks very much for your details reply. 
all my problems are resolved, and I close this issue.

thanks again :)
