### ISSUE TITLE
Cache eternal

### ISSUE THREAD

**Issue by xipito** [cache2k/cache2k#202]
Good morning,
Could you help me about cache setting, in my case cache is eternal and we have expiry setting.

```
   private Cache<TemplateCacheKey, Template> buildTemplateCache(long expirationInSeconds) {
        return Cache2kBuilder.of(TemplateCacheKey.class, Template.class)
            .expireAfterWrite(expirationInSeconds, SECONDS)
            .loader(this::getAppropriateTemplateFromGateway)
            .expiryPolicy((key, value, startTime, currentEntry) -> isNull(value) ? NOW : ETERNAL)
            .build();
    }
```
In this I use
loader(this::getAppropriateTemplateFromGateway)

Another example
```
    private static Cache<TemplateCacheKey, Template> buildTemplateCache(long expirationInSeconds) {
        return Cache2kBuilder.of(TemplateCacheKey.class, Template.class)
            .expireAfterWrite(expirationInSeconds, SECONDS)
            .build();
    }
```
In this I use
methods peek/save

**Comment by globalworming** [comment]
> Could you help me about cache setting

what kind of support do you need?

**Comment by xipito** [comment]
This config   `.expireAfterWrite(expirationInSeconds, SECONDS)`, does not work.

**Comment by globalworming** [comment]
There seems to be some confusion. `eternal` means that entries are kept in the cache forever, they don't expire https://cache2k.org/docs/latest/user-guide.html#eternal

what is it you want the cache to do?

**Comment by globalworming** [comment]
Oh, I think I see what you mean.

```
Expiry.ETERNAL: keep indefinitly or to a maximum of whats set with via expireAfterWrite
```

How do you know that the values are actually not expiring? Do you have cache statistics that confirm these or a minimal project  to reproduce the issue?

**Comment by xipito** [comment]
So, when we update the data, it doesn't reflect, because the cache doesn't update, it stays with the old version.

I have logs from the cache itself


Used Cache.asMap....

**Comment by globalworming** [comment]
and you can confirm that after the expiry time, the cache is returning the old value and not invoking the loader? To be honest I doubt that there is anything wrong with cache2k, so would love to see some minimal, runnable code that reproduces the error.

**Comment by xipito** [comment]
We are evolving, I tested localhost it works, when I tested it on docker+k8s, it doesn't work.

**Comment by globalworming** [comment]
:thinking: there are probably some interesting ways that can mess with your in memory cache. like scaling services down to zero...

as I said, without some kind of example or much more information about how that environment behaves, it's kinda hard to help you

**Comment by xipito** [comment]
Tks
