### ISSUE TITLE
With ExpiryPolicy the cache is called 2 times

### ISSUE THREAD

**Issue by gianluca-valentini** [cache2k/cache2k#205]
Hi,
I'm using cache2k 2.6.1.Final.
I implemente dsome cache bet when I enable the nullValues and set the expiryPolicy (I don't want that the null value is saved for the set expirationTime happens something strange.

Adding a System.out on the user find I see two output for each user that I want to search and cache.

```
cache2k-loader-subjectFactories-1 Loading user User/7d7e4765-bde6-4b36-9779-502587b36cb4
main Loading user User/7d7e4765-bde6-4b36-9779-502587b36cb4
```

When I remove the expiryPolicy it starts to wirk as expected.

Here the configuration of my Cache2kBuilder

```
new Cache2kBuilder<String, User>() {
        }

                .setup(UniversalResiliencePolicy::enable)

                .name("users")

                .expireAfterWrite(1, TimeUnit.MINUTES)

                .permitNullValues(true)

                .expiryPolicy(new ExpiryPolicy<String, User>() {
                    @Override
                    public long calculateExpiryTime(String key, @Nullable Uservalue, long startTime, @Nullable CacheEntry<String, User> currentEntry) {
                        if (value == null) {
                            return NOW;
                        }
                        return REFRESH;
                    }
                })

                .refreshAhead(true) // keep fresh when expiring
                .loader(new CacheLoader<String, User>() {
                    @Override
                    public userload(String key) throws Exception {

                        return loadUser(userid);
                    }
                }).build();
```

I think that there should be something wrong in it but I don't understand where. So I think it could be a bug.
Thanks
Gianluca

**Comment by cruftex** [comment]
@gianluca-valentini 
Replace `REFRESH` with `ETERNAL`. 

Expiry time in the expiry policy is always capped by what you configure in `expireAfterWrite`, so with `ETERNAL` your 1 minute configuration is in effect. If you just don't want to store null values, then this is what to do.

With `REFRESH` you instruct the cache to do an immediate reload and this is what is happening in your case. This is of limited use within `ExpiryPolicy` and more useful with `expireAt`.  I think the documentation of the values could be improved a bit to make that more clear.

Did you copy the code from somewhere?

**Comment by gianluca-valentini** [comment]
Hi @cruftex 
thanks for your answer.
I copied from https://cache2k.org/docs/latest/user-guide.html#null-values 
where was present the code

```
if (value == null) {
          return NO_CACHE;
        }
        return ETERNAL;
```

I didn't found NO_CACHE in the lib. Without example I thought the code allows you to keep the data forever in the cache.
Now it is more clear for me

Thanks
