### ISSUE TITLE
Custom Exception Propagators do not work for Caches that use BulkAction

### ISSUE THREAD

**Issue by yigithanbalci** [cache2k/cache2k#208]
When there is a custom ExceptionPropagator is written to a used cache, it works if there is only a loader is defined. But when there is a bulkloader is defined, somehow the custom exception propagator is not called by the underlying code of the cache. AFAIK there are different types of sub-caches and async one is not calling the propagator defined by the client of API. 

Which is actually work-aroundable. However, it leads to hideous code rather than using the already existing exception handling part of cache2k.

**Comment by cruftex** [comment]
Hi @yigithanbalci! Thanks for the report.

Can you please provide a small snippet of sample code? There are different methods to do the bulk requests and they differ slightly with respect to exception handling.

**Comment by yigithanbalci** [comment]
Hi @cruftex! 

I have tried to recreate the issue on my personal computer since I couldn't share the production code. 
However, I didn't have any issues. It must be a problem with either our own wrapping or maybe some older version. 
I will close this issue since it doesn't exist in the latest version as it seems.

Anyways, thanks for the prompt response to the issue!

**Comment by cruftex** [comment]
@yigithanbalci, no worries. You are welcome!
