### ISSUE TITLE
Interrupted load does not set ProcessingState.DONE, creating hanging threads

### ISSUE THREAD

**Issue by tnf-a** [cache2k/cache2k#212]
I use an ExecutorService to manage concurrent calculations and call invokeAll with a timeout. During these calculations, cache2k is used to fetch data from a database. However, some queries are running longer than the timeout, the threads get interrupted by the ExecutorService and a CacheOperationInterruptedException is being thrown. Stacktrace:

> Caused by: java.lang.InterruptedException
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
> 	at org.cache2k.core.WiredCache.getAllConcurrentLoad(WiredCache.java:538)
> 	... 40 more
> org.cache2k.core.CacheOperationInterruptedException: java.lang.InterruptedException
> 	at org.cache2k.core.CacheOperationInterruptedException.propagate(CacheOperationInterruptedException.java:37)
> 	at org.cache2k.core.WiredCache.getAllConcurrentLoad(WiredCache.java:540)
> 	at org.cache2k.core.WiredCache.getAll(WiredCache.java:453)

This seems to leave the currently handled entry to be in processing state, because when invalidating the cache, the system gets unresponsive and most of the threads are waiting on a single thread that keeps waiting for one entry to be finished processing. Thread dump:

> 3XMTHREADBLOCK     Waiting on: org/cache2k/core/Entry@0x000000064CBABF48 Owned by: <unowned>
> 3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
> 3XMTHREADINFO3           Java callstack:
> 4XESTACKTRACE                at java/lang/Object.waitImpl(Native Method)
> 4XESTACKTRACE                at java/lang/Object.wait(Object.java:248(Compiled Code))
> 4XESTACKTRACE                at java/lang/Object.wait(Object.java:187(Compiled Code))
> 4XESTACKTRACE                at org/cache2k/core/Entry.waitForProcessing(Entry.java:417(Compiled Code))
> 4XESTACKTRACE                at org/cache2k/core/HeapCache.peekAndRemove(HeapCache.java:966(Compiled Code))

Even if I interrupt the process, in Entry.waitForProcessing() the interrupt is ignored and it would wait until the entry has processed - which never happens because the current thread has locked the entry but does not process it.
Is this a bug in cache2k or am I using it wrong?

**Comment by cruftex** [comment]
Thanks for the bug report. Nice to see some heavy usage here.

The two stack traces you sent look normal. The first one with `getAll` is the one waiting for the loaders to complete.

What I can see from your stack trace and `getAllConcurrentLoad` being invoked, that you do not have a bulk loader defined. In this case the loader would be called for a single key, but multiple in parallel via the loader executor.

Most likely, your loaders are still doing something. In this case the entry is blocked for other write operations, which is `peekAndRemove`, until the loading is completed. You send an interrupt to the thread calling `getAll` that is waiting for the loaders to complete. However, this thread is only  triggering the load operations and then waiting. You would need to interrupt the actual load operations running in separate threads as specified by the loader executor.

However, interrupting threads is always problematic. Make sure you understand what is going on. Basically, if the thread is computing something it will not be interrupting by sending interrupt unless the interrupt flag is checked at some point. If you want to interrupt your own operations, I recommend doing your own signalling and not using thread interrupt.

Maybe check what is going on via a thread dump. And then see about how you can make the loaders interruptible.

If you want to timeout a query, better see whether your query API is supporting this. E.g. JDBC has `setQueryTImeout`. Basic TCP connections have timeouts as well.  If you work with interrupting the thread your database connection might still be established and eat up resources.

**Comment by tnf-a** [comment]
Thanks for your fast response, nice to see that the project is still being worked on despite the lack of repo updates. Yes, there is very heavy usage (thousands of requests per minute).

> Most likely, your loaders are still doing something.

This was perfectly right. The loader was working on the entry and blocked a map that was used at the same time by another process which then called invalidate on the entry - which it cannot because it's being processed in the loader. After resolving the deadlock it seems to be working fine. Thanks!
In the second stacktrace above github omitted that the org/cache2k/core/Entry is owned by "unowned", which was confusing me.
