### ISSUE TITLE
List / count the number of open caches

### ISSUE THREAD

**Issue by tburny** [cache2k/cache2k#23]
When unit testing it is desirable to have a standard way to assert that there are no more caches, i.e. that all caches used in unit tests have been properly closed to prevent possible memory leaks.
This is especially true when multiple tests are set up and torn down serially, which might result in duplicate caches if 

This could be done e.g. via 
```
@After
public void tearDown() {
assertFalse("There are no more caches afterCacheManager.getDefault().iterator().hasNext()
}
```

However this approach has two drawbacks:
* A list names for all cache managers has to be known to run this assertion for all caches managed by all cache managers, which is very error prone
* It is quite tedious to write this

As the CacheManager class has a map of all existing cache managers, there should be a method like 
"checkNoMoreCaches()".

Maybe such thing also could be moved to an extra class or class in a module which provides helpers for unit testing caches.
Probably this also could be made part of a JUnit Rule which can be put in any place required.

**Comment by cruftex** [comment]
The idea in genera,l is valid.

However, it is not useful to have a special method for every special use case in the API.

Further more:
Probably the semantics of the CacheManager.iterator() and the whole cache resource management will change in the advent of persistent configuration and persistent storage. The cache iterator will probably iterate also all configured caches.

A way to find out the number of open / used caches by the application makes sense. That should be exposed by a separate management API and/or JMX.

I rename the issue title in that way, hope that is okay.

**Comment by cruftex** [comment]
Closing this, because I think the iterator is good enough for the purpose.
There is no way to iterate cache managers. I don't like putting in something like this, because I am not sure about all its implications when different classloaders and security managers will be present.
