### ISSUE TITLE
OSGi support

### ISSUE THREAD

**Issue by joebrassi** [cache2k/cache2k#27]
The current version 0.22 is not ready for OSGi environments.

To make it ready for OSGi just include the maven plugin
```xml
<plugin>
  <groupId>org.apache.felix</groupId>
  <artifactId>maven-bundle-plugin</artifactId>
  <version>3.0.1</version>
  <extensions>true</extensions>
</plugin>
```
And add the export packages you want to make available for OSGi. [http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html)

**Comment by cruftex** [comment]
Thanks for the input!

To have something quite quick, I can do another release for 0.22. The master needs some work before the next release.

If somebody wants to use OSGi, she probably wants the whole deal. So instead of OSGi-enable all the different Jars (api, core, ee, jmx-api and next jcache) and do a lot of exporting between ourselves, it is probably the best idea to provide a single combined jar and export only the API.

For the latter idea we probably need some testing, whether the API can instantiate the implementations via the service loader.

Should we export the JMX interfaces? I think it is useful, however, exporting them means I need to
keep it as stable as the rest of the API.

Inside one application/JVM we get multiple CacheManagers. By default the name is 'default'. This is used to register the JMX MBeans. The JMX namespaces are not separated, so we probably get some trouble here. Can we get some unique ID from the runtime to use as default, or do we need to force applications to set a unique cache manager name within one JVM?

**Comment by cruftex** [comment]
Spend some time with this. Learned a lot, but no final luck yet. Just capturing what I learned.

For the POM snippet above, you also need to change the packaging type from `jar` to `bundle`. Actually a bundle is a jar, too, but the normal jar manifest info is missing, instead there are only OSGi headers in the manifest. However, I'd like to have the standard headers, like `Implementation-Version`, too.

It is possible to add OSGi information to a standard jar, without changing to bundle packaging:

````xml
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.3</version>
        <executions>
          <execution>
            <id>bundle-manifest</id>
            <phase>process-classes</phase>
            <goals>
              <goal>manifest</goal>
            </goals>
          </execution>
        </executions>
        <extensions>true</extensions>
      </plugin>
````

For cache2k-api, this results in the following manifest:

````
Manifest-Version: 1.0
Bnd-LastModified: 1452409648939
Build-Jdk: 1.8.0_45
Built-By: jeans
Bundle-Description: This package provides only the API needed for compil
 ing. At runtime the module cache2k-core is    also needed.    cache2k i
 s a well engineered high performance in-memory Java cache. It implement
 s    latest eviction algorithms and coding techniques to achieve perfor
 mance about 10 times better    then existing cache solutions. cache2k c
 omes with a clean and concise API. The API is currently    still evolvi
 ng until version 1.0 is reached.
Bundle-DocURL: http://headissue.com
Bundle-License: http://www.gnu.org/licenses/gpl.txt
Bundle-ManifestVersion: 2
Bundle-Name: cache2k API only package
Bundle-SymbolicName: org.cache2k.api
Bundle-Vendor: headissue GmbH, Munich
Bundle-Version: 0.24.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Export-Package: org.cache2k;version="0.24.0";uses:="org.cache2k.spi",org
 .cache2k.storage;version="0.24.0";uses:="org.cache2k.spi",org.cache2k.s
 pi;version="0.24.0";uses:="org.cache2k"
Implementation-Build: ${buildNumber}
Implementation-Title: cache2k API only package
Implementation-Vendor: headissue GmbH, Munich
Implementation-Vendor-Id: org.cache2k
Implementation-Version: 0.24-SNAPSHOT
Originally-Created-By: Apache Maven Bundle Plugin
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Tool: Bnd-2.3.0.201405100607
````

That's nice, but I as mentioned before, for the targeted environments it makes no sense to provide all cache2k artifacts (api, cor, jmx-api, ee and jcache) as separte OSGi bundle.

I tried maven shade and the maven bundle plugin. For some reason, it is not possible to get these two working together. 

It is possible to switch to bundle packaging and instruct the bundle plugin to add the maven dependencies in the bundle. The result is strange. It contains all the contents of the dependencies plus the jar itself (yes, it's a bundle). That is not what we want.

That's what I just checked in. The test result is:

````
java.lang.LinkageError: Error instantiating org.cache2k.spi.Cache2kCoreProvider, got java.io.IOException: Class resource file not found: org/cache2k/services/org.cache2k.spi.Cache2kCoreProvider

	at org.cache2k.spi.SingleProviderResolver.loadProvider(SingleProviderResolver.java:79)
	at org.cache2k.spi.SingleProviderResolver.resolve(SingleProviderResolver.java:64)
	at org.cache2k.CacheBuilder.<clinit>(CacheBuilder.java:21)
	at org.cache2k.test.osgi.OsgiTest.test(OsgiTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
````

Next steps:

 - test whether we can use the manifest goal together with unpack-dependencies from the dependency maven plugin
- look around, how others solve this....

**Comment by joebrassi** [comment]
Hi, 

OK, first, I think there is actually no need to create an API artifact, unless it is strictly needed; you can embed any Interface inside the same Cache2K artifact in an exported package.

Regarding the addition pf OSGi support to Cache2K, don't worry I think I can help you with this. I haven't had the time to check on this thread because I am quite busy at the moment. Anyways, at simple sight I can give you few pointers about your implementation, 

a. The `maven-bundle-plugin` is not correctly configured, there is no need to use "executions" or to call the `maven-bundle-plugin` to execute at any point of the build, it is executed over all artifacts that are packaged as *bundle*. So, in the artifact to OSGify just change the 
```xml
  <packaging>jar</packaging>
```
to 
```xml
  <packaging>bundle</packaging>
```
This will make the `maven-bundle-plugin` to insert the corresponding configuration in the Manifest of the artifact.

b. The only mandatory requirement for OSGi to consider an artifact a bundle, is to have this line in the manifest:
```
Bundle-SymbolicName: com.cache2h.impl
```
The *com.cache2k.impl* is an example of the symbolic name of the bundle. The _Bundle-SymbolicName_ along with the _Bundle-Version_ entry is what makes the bundle uniquely identified inside any OSGi framework.

c. Once you have this basic configuration, you may include some additional entries, like the `Import-Package`. That exception you show is that you are not `Exporting` that package from the bundle where it is, or you are not `Importing` that package where it is used. So, just make sure you have the `org.cache2k.services.org.cache2k.spi`package exported and imported in the bundles where they are Implemented and Used.

d. One last detail, try to avoid using `SNAPSHOT` versions in OSGi, or any version with letters, if I remember well, OSGi cannot match bundle versions that contain letters in it. for example, if you are Exporting a package from a bundle with letters in its version, it is probable that the OSGi framework cannot find the package because it looks to match versions like *0.24.0* and not *0.24.0.SNAPSHOT*. I am not sure if the latest OSGi framework changed this _match_ feature or enhanced it, but the last time I tried using a bundle with letters (few years ago) in its version entry, it simply didn't work. In fact, that may be the cause of that `Class resource not found` you are receiving there.

Later with some time I can surely get into the code to OSGify your artifact in the simplest way, there is no need to be too invasive, only few entries in the Manifest. You can actually do more and create an Activator and publish a Service (the only requisite to publish a service is to make it thread-safe), and make it fully OSGi compliant, but as I said before that is not _strictly_ necessary, the same with the API, an API bundle is sometimes necessary, it is a matter of evaluating the needs for it.

**Comment by joebrassi** [comment]
Reading further in your comment. If you don't want to export a package, then just make it private:

```xml
<plugin>
  <groupId>org.apache.felix</groupId>
  <artifactId>maven-bundle-plugin</artifactId>
  <version>3.0.1</version>
  <configuration>
    <instructions>
      <Bundle-SymbolicName>org.cache2k.services</Bundle-SymbolicName>
      <Bundle-Version>0.24.0</Bundle-Version>
      <Private-Package>org.cache2k.services.internal.*</Private-Package>
    </instructions>
  </configuration>
</plugin>
```

This tells the `maven-bundle-plugin` to not export the package `org.cache2k.services.internal` nor anything inside it.

**Comment by cruftex** [comment]
Maybe there was some confusion. cache2k-api is actually a separate artifact. I just used it as an example to try to make a bundle from an artifact. That worked. 

What I am trying to achieve is:

 * cache2k-all, that contains all artifacts
 * A regular jar, not a bundle, meaning no jars inside the jar
 * OSGi headers in the manifest
 * regular headers in the manifest

Is that actually possible?

**Comment by joebrassi** [comment]
OK, didn't know that cache2k-api was a separate artifact, I thought you created it only for OSGi. 

Regarding your points:

1. cache2k-all, that's a good idea.
2. here you may be confused, because an OSGi bundle is a simple jar with (at least) the `Bundle-SymbolicName` entry in the manifest file. So, you just continue building the cache2k as you always have, with the only addition of the `maven-bundle-plugin` configured in your POM, which will only add few additional headers to the manifest, this will make your artifacts (jars) to work in OSGi and non-OSGi environments.
3. Of course, with the correct configuration of `maven-bundle-plugin` you get the OSGi headers.
4. This one can be done too. In fact, you don't have to sacrifice any of your regular headers because of the use of OSGi headers, remember that for the OSGi to recognize any jar file as an OSGi bundle, it only needs the `Bundle-SymbolicName` in its manifest file, that is all, the rest is just going further in the OSGi direction. Here bellow is an example on how you can add some other headers to the manifest manually during the building of your jar/bundle using an external file `osgi.bnd` in the root of your project:
```xml
<plugin>
  <groupId>org.apache.felix</groupId>
  <artifactId>maven-bundle-plugin</artifactId>
  <configuration>
    <instructions>
      <Bundle-SymbolicName>org.cache2k.services</Bundle-SymbolicName>
      <Bundle-Version>0.24.0</Bundle-Version>
      <_include>-osgi.bnd</_include>
    </instructions>
  </configuration>
</plugin>
```
Then you write the file `osgi.bnd` aside of the `pom.xml` with whatever content you want to include or overwrite in your manifest file. For example:
```
Bundle-Activator: org.cache2k.internal.Activator
MyHeader:some-value
```
Now, when you build the artifact these headers will be included (or overwritten) in the manifest file by the `maven-bundle-plugin`.

**Comment by cruftex** [comment]
Sometimes it helps to take some time off and come back with a fresh look on things. I discovered the parameter that does the trick. With adding inline=true to the line:

````
 <Embed-Dependency>*;scope=provided;inline=true</Embed-Dependency>
````

The bundle plugin does not put the original JARs into the bundle but just the contents. That's what I want...

**Comment by cruftex** [comment]
In 0.23 there is a `cache2k-all` bundle which includes all relevant jar contents and OSGi meta information.
To use it, add the following dependencies:

````
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-api</artifactId>
      <version>0.23</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.cache2k</groupId>
      <artifactId>cache2k-all</artifactId>
      <version>0.23</version>
      <scope>runtime</scope>
    </dependency>
````

The `cache2k-api` package is only used for development / compilation since it is included in `cache2k-all` as well.

**Comment by cruftex** [comment]
Of course, comments highly appreciated :)

**Comment by cruftex** [comment]
Stepped on a in the felix bundler, while testing. The build breaks in case a directory name contains the character '='.
https://issues.apache.org/jira/browse/FELIX-5183
