### ISSUE TITLE
Support industry standard health checks via JMX

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#28]
cache2k is already enabled for a simple health check: `CacheInfoMXBean.getAlert()`
1. Support the established convention how this is exported: http://hawtio.github.io/hawtio/plugins/health/
2. The 'Warning' alert can have many different causes. At the moment there is text hint to the cause, instead an administrator would need to investigate all the statistic values. Make some text available that briefly describes the warning cause.

The relevant definition is:

- *level*: The severity level such as INFO, WARN, ERROR, CRITICAL to give some indication of how serious the problem is. INFO means its OK and healthy.
- *message*: A textual description of the health check status.

**Comment by Stephan972** [comment]
As of this writing, http://hawt.io/plugins/health link returns 404 error.

**Comment by cruftex** [comment]
Seemed to be removed from the webpage. Its still here:

http://hawtio.github.io/hawtio/plugins/health/

**Comment by cruftex** [comment]
In #150 we will go through all the statistics. Bundle.

**Comment by cruftex** [comment]
Closing. Happy to reopen, in case of real there is a good usage example
