### ISSUE TITLE
Global shared timer / reduce threads used for expiry timers

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#37]
Currently each cache needs a timer thread, in case expiry is enabled. An extra thread per cache might be quite resource intensive, in case there are many caches.

Use a shared timer for all caches. The timer needs to handle enough concurrency.

**Comment by DALDEI** [comment]
I just noticed this myself - quite supprised at allocation of a long lived thread *per cache* -- (not per cache manager?)
Any progress on this ? Its causing me to hesitate making further use of the library  knowing every cache In put in is allocating a permanent thread.

**Comment by cruftex** [comment]
The timer thread is only needed, when expiry is used.

This is one of the features I postponed in order to finish up the 1.0 version. I did focus on a clean API and on a feature set that works for us in production for many years (actually, decades...).

Looking at the whole picture, cache2k has a quite compact memory footprint and lower GC throughput, when compared to other caches. I doubt that the extra thread has a big negative impact. A separate thread limits the risk that caches influence each other.

I have rough plans about doing a 2.0 version which also tackles this over the next months. The 1.X versions are still compatible with Java 1.6. When addressing this, I'd like to use a (more) recent version of Java.

If anybody has serious pains about this or ideas and wishes, any further input is highly appreciated.

**Comment by cruftex** [comment]
This will be resolved with version 1.6. The changes are committed already.
The new code uses two shared threads to trigger the execution of timer tasks for all caches. The actual execution of the timer tasks is delegated to the common ForkJoinPool to make use of all CPUs if there are many caches needing expiry. Timer tasks are gathered together and executed in bulks within an approximate one second interval. In case an expiry listener is configured, each task will executed separately.

Expiry events and the removal of cache entry may lag up to one second. This behavior is similar to Caffeine and should be acceptable. The lag time is configurable via `Cache2kBuilder.timerLag`

Still running tests and validation on this, so keeping the issue open.

**Comment by cruftex** [comment]
This was released in 1.6
