### ISSUE TITLE
Expiry Listener

### ISSUE THREAD

**Issue by crumbpicker** [cache2k/cache2k#38]
In some situations it may be interesting to have a callback fired just before the expiration of a given entry. It would provide a control over this detached entry. 

For instance if the expired entry has some allocated resources, it may be required to close the resources before losing a reference to the corresponding object.

Without this feature, it is mandatory to handle a separate cache of the same entries without any expiration and to check manually and periodically if a given entry expired. This is possible but I think that cache2k could provide such a feature.

Thanks !

**Comment by cruftex** [comment]
I understand the idea.

In the git master there are already events for creation, update and removal. Expiration and Eviction need to be done.

Questions:

What is the meaning of "before" in this scenario? If you need to free resources it would be incorrect if the cache is still returning the values while the callback is freeing the resources. So I think the call needs to be done after the entry is not more accessible through the cache, correct?

Although I understand the idea, I'd like to have an idea of real world scenario where hit is useful. Can you give one or two practical examples or describe you specific use case?

**Comment by crumbpicker** [comment]
There is no special meaning in the described scenario, the callback would just need a reference to the expired entry. So you're right it could be fired before or after expiration.

**Comment by cruftex** [comment]
Gotcha, thanks for the two interesting use cases. Also it feels pretty much like a caching problem its a little bit atypical for an in memory cache like cache2k or any other member of the caching club.

Quantities: I expect that these are not more than 100. The "heavy" stuff is the associated resources, not the cached entries them self. That means the control structures could stay in memory. Can you edit your previous post and add some quantities.

API: While it is desirable to have a centralized resource management, it is not nice for each component to deal with a cache-like K/V interface to get "its" entity manager. I always suspect that some newbie might just keep the reference. A supplier or holder pattern would be nicer. Of course you can hide a real cache behind that, too.

So as an alternatively a single object who is doing the needed things would be doable, too. This is more overhead per item, but okay for small quantities. Personally I would like to see an extended version of the `Suppliers.memoizeWithExpiration` from Guava that can do this...

Some notes (to myself....):

That is also an example for expire after access. Currently cache2k only has expiry after modification. There are some tricks to do expire after access, however, that needs a proper interface.
Using exipry after modification is feasible, but means that an entry gets refreshed when still in use.

For that kind of usecase it would be nice if the cache provides a `Supplier` like interface, too. Maybe that's worth considering alongside the async support.

Using this issue to track support for the expiry listener. Will look into that beginning of march.

**Comment by cruftex** [comment]
Added also: https://github.com/cache2k/cache2k/issues/39

**Comment by crumbpicker** [comment]
I agree its not a typical use of the usual cache pattern. Here this is more the expiry feature which is of interest.
But the only libraries offering the expiry feature are caching lib like cache2k and the Guava Cache API.

I agree with you about the good practice of cache usage in the context of EntityManager. However I don't think this is the responsibility of the caching library to take care about this. I think you can provide something very simple like executing a Callable<T> when an expiry event is fired. You don't have to care about what is done inside the Callable code. IMHO this is the responsibility of the dev who is using this API.

**Comment by cruftex** [comment]
> I think you can provide something very simple like executing a Callable when an expiry event is fired. You don't have to care about what is done inside the Callable code. IMHO this is the responsibility of the dev who is using this API.

Yes, and the more flexibility you have to do useful things, the better ;)

Its not totally simple for cache2k, since there is the persistence feature. So everything needs to work with billions of entries, not necessarily residing in heap memory, too :(

Take a look also at this, which could be well sufficient for your usecase:
https://github.com/jhalterman/expiringmap

**Comment by crumbpicker** [comment]
Thank you very much !
It is exactly what I was searching :D
I was not able to find this library when searching on google.
I think I will use this lib for my applications but I'm sure I'll find other usages for cache2k ;-)
I'll let you decide about the potential interest for cache2k.
Best.

**Comment by cruftex** [comment]
You are welcome!

**Comment by cruftex** [comment]
Just committed the expiry listeners code, included in next release.

**Comment by hari-rangarajan** [comment]
Do you plan to add one for eviction? The doc says it is not available. Thanks!

**Comment by cruftex** [comment]
There is no plan to add an eviction listener at the moment. Before adding new features I'd like to learn more about potential applications. @hari-rangarajan:  If you are interested in this, please open a new issue and describe what kind of problem you want to solve with the eviction listener. Thanks!
