### ISSUE TITLE
Expiry after Access / Time to Idle

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#39]
Support of expiry after an entry is accessed is missing in core cache2k.

*What is it?*

An entry expires and is removed from the cache after being not accessed for a period of time. The main use is primarily for freeing resources and shrinking the cache when the application is not in use.

*Current state:*

The feature is available in the JCache support. However, it is not implemented very efficiently. Also, the standard functionality of JCache is not very practicable. JCache defines TTI, however it cannot be combined with expire after write.

*Why it isn't available in cache2k, yet?*

We almost never need it. Typically we run caches with a TTL between 30 seconds and 30 minutes. Which means that entries expire via the TTL setting and the cache shrinks. TTI would be needed if entries never expire via TTL or have a higher TTL than TTI. For example a web resource might be allowed to be cached for 6 days, however, if being not accessed we like to remove it from memory after one hour.

The second reason is the overhead. TTI is typically implemented via an LRU style linked list. This brings lock contention and concurrency issues.

*Solutions*

If needed several options are available via the existing cache2k features, e.g. the expiry can be modified in a cache request via the entry processor.

We also plan to do an efficient implementation of a TTI approximation which is based on the eviction algorithm.

**Comment by ricardojlrufino** [comment]
What status of this implementation?
The main feature I needed was this ...

**Comment by quaff** [comment]
`Ilde` in title should be `idle`

**Comment by cruftex** [comment]
@quaff Oops, thanks, I changed the title!

**Comment by cruftex** [comment]
@ricardojlrufino Thanks for reaching out! Its good timing, since I have now stabilized the next version (1.2) and need to do some planing what important stuff to put the focus on next.

Two reasons it's not there yet: We rarely need it, there needs to be always a compromise on the performance we have achieved to provide/enable this feature.

To drive it in the right direction, I'd love to hear from people who actually need it. Can you share something about the scenario you want to use it for?

**Comment by ricardojlrufino** [comment]
@cruftex My application is from IoT and I cache the Devices in use and, after a while, I need to remove it from memory.
I ended up using the Guava library, unfortunately it is very large (2MB), and I only use it for cache.

Ref: https://github.com/google/guava/wiki/CachesExplained

**Comment by detohaz** [comment]
@cruftex This is an very important feature that I need now. I have more than 100 million elements to cache, but not all of them are accessed continuously (~ 5 millions). The cache eats  my ram (> 70Gbs) so I cannot run two instances simultaneously (total 125Gbs).
I have divided into smaller partitions (32 partitions) to improve access time, and now I'm dealing with memory problems.
Hope that this feature will be implemented as soon as possible.
Thank @cruftex.

**Comment by cruftex** [comment]
@detohaz, @ricardojlrufino: Thanks for your feedback! Unfortunately, I am a bit held up with other activities but there will be some progress here during 2019... For the use cases you describe I still wonder whether TTI is really the best solution. So I like to move in two directions here: Implement TTI but also maybe come up with a better cache feature for 90% of the use cases that use TTI now.

@detohaz: You know that around 5 million entries are accessed continuously and should therefore be cached. What about limiting the cache size to 8 million entries and keep the ram usage in check?

**Comment by cruftex** [comment]
@detohaz: Did my suggestion to limit the cache size help and solve your problem?

In case you use a TTI like feature, the actual cache size would depend on the usage pattern. This can lower your heap memory usage, in times when you have low utilization. However, you don't have a guarantee for an upper memory limit.

**Comment by xuyenhabinh** [comment]
Hey cruftex, it's detohaz! This is my new identity.
It's exciting to hear you share about your improvements. Keep up the work as I always support this project.

**Comment by cruftex** [comment]
As promised some comparison data. For the comparison I use a recorded trace, which I included in the last commit.

_About the trace:_

Access trace on the product catalog on an eCommerce website of 24 hours starting from 4am goining to 4am the next morning. All requests of robots (web spiders from search engines like Google or Bing) were removed, so the trace contains mostly user activity. The requests were reduced by removing a random selection of keys to have a more compact sice for including in the project. The first integer of the trace is the time in seconds, the second one the accessed key. Both integers are normalized and starting at 0. The trace characteristics are: 
**Request count: 66319, unique keys: 8810, maximum hitrate: 86.72**

For the comparison I implemented the established semantics (removal exactly after passing the idle duration), plus and run a playback of the above trace. Next I run the playback against the current cache2k code via a simulated clock source.

Find the code and traces via the referenced commit above.

_Established Time To Idle semantics_
| TTI/Minutes | Maximum cache size | Average cache size | Hitrate |
|---:|---:|---:|---:|
| 55 | 3789 | 1370 | 70.09
| 56 | 3799 | 1386 | 70.29
| 57 | 3825 | 1402 | 70.47
| 58 | 3831 | 1417 | 70.66
| 59 | 3858 | 1432 | 70.87
| 60 | 3867 | 1448 | 71.03
| 61 | 3889 | 1463 | 71.18
| 62 | 3923 | 1478 | 71.35
| 63 | 3984 | 1493 | 71.49
| 64 | 4002 | 1507 | 71.65
| 65 | 4027 | 1522 | 71.83

_Time To Idle emulation via scanning in cache2k 2.6_
| Scan round time/Minutes | Maximum cache size | Average cache size | Hitrate |
|---:|---:|---:|---:|
| 25 | 3094 | 1311 | 70.72
| 26 | 3005 | 1347 | 71.15
| 27 | 2821 | 1350 | 71.19
| 28 | 3599 | 1408 | 71.87
| 29 | 3139 | 1440 | 72.18
| 30 | 3451 | 1454 | 72.42
| 31 | 3890 | 1467 | 72.55
| 32 | 4239 | 1517 | 73.13
| 33 | 4183 | 1533 | 73.25
| 34 | 4180 | 1576 | 73.63
| 35 | 4268 | 1610 | 74.06

Using about half of the TTI as scan time, produces a similar average cache size, while having a better hitrate and a lower maximum cache size. Thus, saving resources while being more effective.

With the established TTI semantics resource usage is growing or shrinking linear with the time setting. With the scanning approach the resource numbers are "jumping". This can happen because the results depend on how the scanning activity aligns with the requests. This could be improved by doing more scan rounds, at the expense of higher overhead. However, there should be more investigation, since the jumps in the maximum cache size between 29 and 32 minutes are quite big and unexpected.

For the above results cache2k runs with unbounded capacity and the eviction algorithm is not working as regular. Instead of splitting up the data between a cold and hot set, everything is in the hot set, or, one clock data structure that is scanned through. The next test is combined with normal eviction activity by setting the capacity to 2000 entries.

_Time To Idle emulation via scanning in cache2k 2.6 with capacity limit of 2000 entries_
| Scan round time/Minutes | Maximum cache size | Average cache size | Hitrate |
|---:|---:|---:|---:|
| 25 | 2000 | 1255 | 70.61
| 26 | 2000 | 1287 | 71.04
| 27 | 2000 | 1308 | 71.13
| 28 | 2000 | 1337 | 71.73
| 29 | 2000 | 1366 | 72.13
| 30 | 2000 | 1395 | 72.33
| 31 | 2000 | 1410 | 72.56
| 32 | 2000 | 1433 | 72.91
| 33 | 2000 | 1447 | 73.03
| 34 | 2000 | 1475 | 73.32
| 35 | 2000 | 1514 | 73.86

_Conclusion:_

While there is more validation and testing work to do, it can be seen that the general direction makes sense and the approach is a valid alternative to the established straight forward TTI implementation.

When we cap the cache size to 2000 entries the scanning TTI emulation runs in cooperation with the normal eviction resulting in a lower maximum cache size but not much lower hit rates. That means there is potential for more improvement by making more use of the eviction algorithm, e.g. by removing "idle" entries faster that had never seen any hits.

I see different directions of "improvement":
- A closer emulation of the original TTI semantics, for example, by doing multiple scan rounds and removing entries after several rounds idling
- Instead of more predictable TTI semantics going the other direction and improve efficiency, e.g. by removing cold entries faster as hot entries

For now I will stabilize the current approach, which seems "good enough" to make it into production and then we can learn from it.

**Comment by cruftex** [comment]
Did some more testing and fixed an logical error that lead to one round scan and one round pausing. Corrected the numbers in the previous comment.

Here is a histogram of the actual time from last access to eviction for the 45 minutes scan time setting:

| Idle time until eviction | Count | Count as Bar |
|---:|---:|:---|
| 35 | 112 | : | 
| 40 | 5545 | ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: | 
| 45 | 7967 | :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: | 
| 50 | 741 | :::::::: | 
| 55 | 655 | ::::::: | 
| 60 | 653 | ::::::: | 
| 65 | 470 | ::::: | 
| 70 | 414 | :::: | 
| 75 | 460 | ::::: | 
| 80 | 544 | :::::: | 
| 85 | 948 | :::::::::: | 
| 90 | 711 | ::::::: | 
| 95 | 45 |  | 
| 100 | 16 |  | 
| 105 | 8 |  | 

The time column represents a time span of 5 minutes.

Idle evictions between 45 and 90 minutes could be expected, however we see evictions a bit before and after. Longer times are happening during a phase of cache growing, smaller times are happening during a phase of cache shrinking.

As an example let's look at the shrink phase: One entry could be in the middle of the scan round. If most of the entries are removed in the round, the entry would be at the beginning of the next scan round. This means there is a chance that entries are removed much earlier during shrinking.

These outliers are not problematic, the opposite, the behavior is in sync with the workload phase. During the insert phase (rising activity) it makes sense to keep entries a bit longer, during the shrink phase (ebbing activity) evictions can be done earlier without doing harm.

**Comment by cruftex** [comment]
Notes on compensating for inserts and removals while scanning:

_Inserts_ There is no compensation for inserts. We could speed up the scan since the cache size increases, however, this happens at the start of the new round anyway.
_Removals_ Entries might be removed by `Cache.remove` or expiry. In this case we would scan too much when keeping the original scan speed. We compensate and reduce the amount of remaining scans. We need to differentiate entries that were already scanned in the round and entries not yet scanned. Therefore each entry is tagged with a round counter which means the entry was scanned. Entries removed and not yet scanned will lower the scan rate accordingly. Inserts always happen with the current round tag, so if something is inserted and removed in the same round, no compensation is done.

**Comment by cruftex** [comment]
Completed and shipped a while ago in:
https://github.com/cache2k/cache2k/releases/tag/v2.5.1.Alpha
Latest release for testing it:
https://github.com/cache2k/cache2k/releases/tag/v2.5.3.Beta
