### ISSUE TITLE
StackOverflowError when using Cache.asMap()

### ISSUE THREAD

**Issue by TheGoodlike13** [cache2k/cache2k#51]
Hi there,

From my understanding, Cache.asMap() wraps the Cache object in a ConcurrentMapWrapper. In this class, the methods keySet(), values() and entrySet() are implemented using AbstractSet. 
The problem is that AbstractSet.size() method was implemented as "return size()", which recursively calls itself and crashes whenever size() is called.
I believe the intent was to call ConcurrentMapWrapper.size() instead, in which case it should be implemented as "return ConcurrentMapWrapper.this.size()"

Sorry for poor formatting or w/e, first time creating an issue.

P.S. forgot to mention, it was version 0.27-BETA

**Comment by cruftex** [comment]
Thanks for reporting this. You are totally correct, that is a (stupid...) bug. Can you do a workaround for the moment or should I publish a fixed version ASAP?

**Comment by TheGoodlike13** [comment]
I have worked around it by extending ConcurrentMapWrapper and overriding the appropriate methods with the fix, as you can see here:
https://github.com/TheGoodlike13/twitch-sahyun-bot/blob/master/src/main/java/eu/goodlike/sahyun/bot/http/cookies/CorrectConcurrentMapView.java

Then instead of Cache.asMap() I manually cast the Cache into InternalCache and use the constructor.
It's not pretty, but it works :)

**Comment by cruftex** [comment]
Fix released.
