### ISSUE TITLE
Cache2kBuilder.permitNullValues() javadoc mistake

### ISSUE THREAD

**Issue by boolivar** [cache2k/cache2k#54]
Looks like there is a mistake in javadoc for permitNullValues property:
https://github.com/cache2k/cache2k/blob/fd97248461f8ad4d3c6e92bb88a45572dd6f2390/cache2k-api/src/main/java/org/cache2k/Cache2kBuilder.java#L597
By default null values not permited, also true value here conversely prevents exception throwing.

**Comment by cruftex** [comment]
Thanks, great find! I did reverse the meaning, it was rejectNullValues before, but missed to correct the Java Doc.

BTW: I wrote a little more about nulls here:
https://github.com/cache2k/cache2k/blob/master/documentation/src/docs/asciidoc/user-guide/sections/_null.adoc
