### ISSUE TITLE
Default settings not mentioned in Docs

### ISSUE THREAD

**Issue by neuweiler** [cache2k/cache2k#58]
Unless scanning the code, it's not possible to figure out the default values used by cache2k - e.g. if you use a cache loader without args.

**Comment by cruftex** [comment]
Default values for configuration parameters are documented in the Java Doc of the `Cache2kBuilder`.
Probably the user guide should refer to it at some place.

> ... e.g. if you use a cache loader without args.

What does that mean? Can you give an example?

**Comment by cruftex** [comment]
Tried to improve the JavaDoc a little. Still unsure where/what might be still missing.
