### ISSUE TITLE
Scheduler for Timeout test

### ISSUE THREAD

**Issue by SergejIsbrecht** [cache2k/cache2k#60]
It would be good, if there would be something simular to RxJavas Scheduler-interface to virtually move time for testing purpose.
`.expireAfterWrite(60, TimeUnit.SECONDS, testScheduler)`

TestScheduler would provide a mathod like: advanceTimeBy(long time, TimeUnit unit)
`testScheduler.advanceTimeBy(60, TimeUnit.SECONDS)`

Documentation of Scheduler and Testscheduler:
TestScheduler: http://reactivex.io/RxJava/javadoc/rx/schedulers/TestScheduler.html
Scheduler: http://reactivex.io/RxJava/javadoc/rx/Scheduler.html

**Comment by cruftex** [comment]
Guava and caffeine have an interface called Ticker, that let you do that. Further described in:
http://stackoverflow.com/questions/29990788/guava-ticker-cache-expire
https://github.com/ben-manes/caffeine/wiki/Testing

For the next cache2k version I plan to introduce something similar, but probably only for internal testing. Putting it on the public API makes it hard to further evolve.

So far I have not seen an example, where you really need it to reach 100% test coverage. Do you like to share a simple use case of yours?

**Comment by cruftex** [comment]
The upcoming version has a configurable time reference, this is already released in a preview version.
Its main use is to fully test all of the cache2k functionality that depends on time. This is only meant for internal use, I don't want to encourage using this for further testing, so I don't make it available on the public API. Maybe I could make it available in a separate testing module, if there are good reasons for it.
If curious, see:

- https://github.com/cache2k/cache2k/blob/master/cache2k-impl/src/main/java/org/cache2k/core/util/InternalClock.java
- https://github.com/cache2k/cache2k/blob/master/cache2k-impl/src/test/java/org/cache2k/core/util/SimulatedClock.java

For testing of application code that depends on time, I recommend not to use not a separate time source, at least when used with cache2k. The cache2k API has the `AdvancedCacheLoader` and the `ExpiryPolicy` get the relevant time information as parameter. Application code that depends on time, should always accept it as a parameter and not use the system clock.
