### ISSUE TITLE
How to add cache2k dependency to gradle project

### ISSUE THREAD

**Issue by swarooppallapothu** [cache2k/cache2k#61]
I have a gradle application. I want to add cache2k dependency to my gradle project. How i do this

my build.gradle
apply plugin: 'java'

sourceCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

if (!hasProperty('mainClass')) {
    ext.mainClass = ''
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.cache2k:cache2k-api:1.0.0.CR4'
    compile 'org.cache2k:cache2k-all:1.0.0.CR4'
    testCompile group: 'junit', name: 'junit', version: '4.10'
}

**Comment by cruftex** [comment]
Good question. I am not a gradle user but I hope we can figure it out together. From what I read in the gradle docs, I think this is the correct way:

````
repositories {
  mavenCentral()
}
dependencies {
  compileOnly 'org.cache2k:cache2k-api:1.0.0.CR4'
  runtime 'org.cache2k:cache2k-all:1.0.0.CR4'
}
````

With `cache2k-api` as compile only dependency, it is ensured that you only use official API your program. For the runtime the `cach2k-all` includes everything needed, the implementation and the API.

Please give some feedback whether this works as intended. I will also do a small gradle test project by myself to test that.

**Comment by swarooppallapothu** [comment]
It is working Thanks.

**Comment by swarooppallapothu** [comment]
Now it is working.

Thanks
