### ISSUE TITLE
Typos in Documentation

### ISSUE THREAD

**Issue by tburny** [cache2k/cache2k#63]
Version: 1.0.0.CR4

https://cache2k.org/docs/1.0/apidocs/cache2k-api/src-html/org/cache2k/Cache2kBuilder.html#line.502

"at leas" is missing "t"

https://cache2k.org/docs/1.0/apidocs/cache2k-api/src-html/org/cache2k/integration/AdvancedCacheLoader.html#line.46

"und" instead of and

**Comment by cruftex** [comment]
Thanks!
