### ISSUE TITLE
Why cache name can't contain characher:'#'?

### ISSUE THREAD

**Issue by ChiZelin** [cache2k/cache2k#65]
Excuse me, could you please tell me that,when you design the Cache2k,why not allow cache name contains characher : '#' ? What's the advantage of doing this?  

Thank you!

**Comment by cruftex** [comment]
Hi Leon!

The main reason character are restricted, is the use in the JMX object name. Although a '#' is allowed in an object name, I decided to be more restrictive and don't allow any special characters in URLs. This way I hope not to get into trouble for future extensions when a cache name may be used in a file name, for example.

Why you want to use '#'? Is there any standard/convention/product that needs it?

**Comment by ChiZelin** [comment]
Hi Jens!

Thank you for your reply.

I try to use cache2k in a project, the project has identified the cache name and the cache name contains "#".

**Comment by cruftex** [comment]
I am revisiting what characters we can allow. The JMX tests are passing, when using a '#'.

**Comment by ChiZelin** [comment]
OK,Thanks.

**Comment by cruftex** [comment]
The following characters will be additionally allowed +!'%#
Will be released in 1.0.0.Final.

**Comment by cruftex** [comment]
The release 1.0.0.Final is now available.

**Comment by ChiZelin** [comment]
OK,thank you!
