### ISSUE TITLE
JCache for Android

### ISSUE THREAD

**Issue by rfc2822** [cache2k/cache2k#73]
Hello,

As far as I have seen, cache2k can be used
1. as JCache implementation,
2. stand-alone for Android.

However, I'd need a combination of both for an Android app which uses another library (ical4j) which now requires a JCache implementation.

Using the cache2k JCache implementation doesn't work on Android because it seems to rely on `javax.naming`, which is not available on Android. Is this limitation by the JCache API itself or would it be possible to change the implementation so that it doesn't depend on `javax.naming`? (In the latter case, I could also try to get it working and submit a patch.)

**Comment by cruftex** [comment]
**`javax.naming`**:

In code intended to run on a server, cache2k uses a JNDI lookup to change the default name of the cache manager. The implementation is here:
https://github.com/cache2k/cache2k/blob/master/cache2k-server-side/src/main/java/org/cache2k/ee/impl/JndiDefaultNameProvider.java

The idea behind that is, to have a mechanism to get unique names of cache managers if multiple applications run inside a single application server (e.g. Tomcat). It may be that nobody uses this any more. It should be either removed, or properly documented. Somehow it slipped through in the 1.0 finalization process.

**JCache for Andriod**

The JCache Spec targets Java 6, but requires that every cache implementation is supporting JMX. JMX is not present on Android. The JCache `CacheManager` class has a dependency on `java.lang.management.ManagementFactory`. This is major problem and I am not sure whether there are other dependencies as well. cache2k supports API level 16. I am not 100% whether this is still a problem with later API levels.

**Comment by cruftex** [comment]
Closing this. There isn't much I can do here.

Maybe JCache should get rid of the dependency to JMX in the core API. That would be better in terms of modularity anyway.
