### ISSUE TITLE
Logging disregards slf4j nop settings

### ISSUE THREAD

**Issue by bobbotron** [cache2k/cache2k#77]
This project actively ignores slf4j no operation implementation.  This is breaks the spirit of how slf4j logging projects are supposed to work.

This is interfering with automated testing in a project I work on, where this output is distracting in our build output.

https://github.com/cache2k/cache2k/blob/53544af89227ecd451d7d7fc669af0d18beb88ff/cache2k-core/src/main/java/org/cache2k/core/util/Log.java#L84

**Comment by cruftex** [comment]
Thanks for the issue. That's a relevant point. The presence of the `NOPLoggerFactory` can mean two things:

1. The logging is switched off
2. There are multiple log frameworks included and logging via SLF4J is switched off by including the dependency `slf4j-nop`. 

The code passage is there for the reason 2. In your scenario the logging auto detection probably falls back to JDK logging.

Possible solutions with the current version:
- Bridge JDK/JUL logging to SLF4J
- Switch off cache2k logging in the JDK logger (`org.cache2k=OFF`)

I'll check with the other projects, whether we can remove this check.
