### ISSUE TITLE
XSD schema for XML configuration

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#79]
The cache2k XML confugration should have a XSD definition.

Examples of other caches:
- http://www.ehcache.org/ehcache.xsd
- http://infinispan.org/schemas/infinispan-config-7.0.xsd
- https://hazelcast.com/schema/config/hazelcast-config-3.9.xsd

Todo:
- the configuration files `cache2k.xml`, `cache2k-example.xml`, `cache2k-customizationExaple.xml`, within the `cache2k-xml-configuration` test resources need to pass the XSD
- the configuration files `cache2k-jcacheExample.xml`, within the `cache2k-jcache` test resources need to pass the XSD
- the XSD should contain all properties from the "Java bean"  `Cache2kConfiguration`
- the XSD should contain all properties from the "Java bean"  `JCacheConfiguration`
- the XSD should also contain the description of the properties that can be found in the `Cache2kBuilder`, see the above examples from the other caches

Additional hints:
- Documentation on the XML configuration  is here: https://cache2k.org/docs/1.0/user-guide.html#xml-configuration
- The documentation lacks description on sections. I have put some comments in `cache2k-jcacheExample.xml`
- not everything can be covered by the XSD, e.g. the properties or custom suppliers.
- copying around the descriptions will be tedious. We need to do it for any major release

**Comment by nenko-tabakov** [comment]
Have you considered using JAXB?

**Comment by cruftex** [comment]
Yes. I looked into various existing tools. The implemented XML-configuration library also works on Android. There is also support for templates and expansion of variables.

**Comment by Rokia88** [comment]
Hi everyone, 

I am currently working on this issue, I appreciate if you can explain to me the problem in detail and the solutions you have tried to solve it. Thank you.

**Comment by cruftex** [comment]
@Rokia88 great you are looking into this! I updated the description for more details.

**Comment by cruftex** [comment]
The schema is available now at:
https://cache2k.org/schema/cache2k-core-v1.x.xsd
