### ISSUE TITLE
No implementation found for: org.cache2k.spi.Cache2kCoreProvider

### ISSUE THREAD

**Issue by zhljen** [cache2k/cache2k#81]
I am using this in Spring to build the cache, and get an exception.  think I must miss something. Let me know how to resolve it
 new Cache2kBuilder<String, Optional<ObjectNode>>() {
        }.name("databaseMetadataCache")
            .entryCapacity(50)
            .expireAfterWrite(5, TimeUnit.MINUTES)
            .permitNullValues(true)
            .build();
java.lang.LinkageError: No implementation found for: org.cache2k.spi.Cache2kCoreProvider

**Comment by cruftex** [comment]
Please check that you have the jars/modules `cache2k-all` or `cache2k-core` included.

See: https://cache2k.org/docs/1.0/user-guide.html#getting-started

**Comment by cruftex** [comment]
Hope the answer above helped. Closing.
