### ISSUE TITLE
Remove support for CacheEntry.getLastModification

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#84]
The property `CacheEntry.getLastModification` has many years history within our applications.
Since the cache does check the time for expiry calculations, I found it is a good idea to keep track of the last modification time by default. It seemed that it comes with no additional cost.

Usages we have:

- Use the timestamp for HTTP requests with `if-modfied-since` via the `AdvancedCacheLoader` interface
- Use it for delta-calculations in the `ExpiryPolicy` to adapt the expiry duration with the variance of changed data in a time span

The problem:

Since `CacheEntry.getValue` and `CacheEntry.getLastModfied` are two separate fields, we need to do extra synchronization for the methods `getEntry` and `peekEntry` to return a consistent `CacheEntry`.

Also, when the cached value comes from another cache or storage, the actual modification date of the cache2k cache entry is meaningless for calculations.

That means the better option is to add a modification timestamp to the value, if that is needed and drop this feature from `CacheEntry`.

This is open for discussion / consideration.

**Comment by cruftex** [comment]
Did some research in existing applications:

2 out of 100 caches use `CacheEntry.getLastModification` and those usages can be easily replaced

So we don't need to expose the modification time in the `CacheEntry`. The time is still needed internally, since we use it for expiry and resilience calculations.

Decision:
Disable `CacheEntry.getLastModification` but keep it internally to support the time based calculations.

**Comment by cruftex** [comment]
Just released with 1.1.2.Alpha

**Comment by hlavki** [comment]
@cruftex, could you please provide way how can I access `MutableCacheEntry.getRefreshedTime()` from `AdvancedCacheLoader`. thanks

**Comment by cruftex** [comment]
@hlavki,

to get the refreshed time, the most compact variant is:

````
    long refreshedTime = cache.invoke(key, e -> e.getRefreshedTime());
````

Behind that is the concept of the `EntryProcessor` which operates on a `MutableCacheEntry`. You can find two more examples about the entry processor in the [user guide](https://cache2k.org/docs/latest/user-guide.html#entry-processor)

If you need the value and the corresponding refreshed time, doing two separate calls to the cache does not give a consistent result. That is unfortunate in some use cases. For example:

````
    V value = cache.get(key);
    long refreshedTime = cache.invoke(key, e -> e.getRefreshedTime());
````

After the call to `cache.get` the value might be refreshed and the returned time could already reflect the updated one. A consistent view is available during the execution of the `EntryProcessor`. For example:

````
    Tuple t = cache.invoke(key, e -> new Tuple(e.getValue(), e.getRefreshedTime()));
````

This extracts value and time within one atomic cache operation.
