### ISSUE TITLE
Is it possible to make a MicroMeter.io integration for Metrics?

### ISSUE THREAD

**Issue by dave08** [cache2k/cache2k#95]
This would allow the standard JMX, and also open the doors to having Prometheus and other types. Since Prometheus is so widely used (like in Docker and Kubernetes), it could be a very important addition to this 
great library.

**Comment by cruftex** [comment]
That's a good idea. I checked the documentation and found an example for Guava cache:

    Cache cache = ...; // suppose we have a Guava cache with stats recording on
    registry.more().counter("evictions", tags, cache, c -> c.stats().evictionCount());

From: http://micrometer.io/docs/concepts

The internals of cache2k allow that you add additional functionality in a separate jar module. The monitoring extension can implement the CacheLifecycleListner SPI:

    public interface CacheLifeCycleListener {
      void cacheCreated(Cache c, final Cache2kConfiguration cfg);
      void cacheDestroyed(Cache c);
    }

https://github.com/cache2k/cache2k/blob/master/cache2k-core/src/main/java/org/cache2k/core/spi/CacheLifeCycleListener.java

So yes, its easily possible.

**Comment by cruftex** [comment]
See: https://github.com/cache2k/cache2k/issues/120

For micrometer its better that you can access the statistics directly. In 1.4 I add `Cache.getStatistics()`. Once the methods are in the API, we can add cache2k support to micrometer.

**Comment by cruftex** [comment]
Just added micrometer support in the repo. I decided to ship it as a separate module in `cache2k-micrometer` and access the internal statistics API of cache2k, rather then add a `getStatistics()` to the public API.

**Comment by cruftex** [comment]
Ooops, forgot to close this issue. This was delivered with version 1.4 released recently.
