### ISSUE TITLE
Remove randomized hashing (?)

### ISSUE THREAD

**Issue by cruftex** [cache2k/cache2k#96]
cache2k has its own hash table implementation and does randomize the hash table for security reasons. The topic is explained in this blog post:

https://lemire.me/blog/2012/01/17/use-random-hashing-if-you-care-about-security/

The current implementation calculates a derived hash value and XORs a random number to it.
The code is:

    public int modifiedHash(int h) {
       h ^= hashSeed;
       h ^= h >>> 7;
       h ^= h >>> 15;
       return h;
    }

The actual `hashSeed` is different for each cache instance.

Looking on other caches, namely, Caffeine, EHCache3 and Guava Cache, nobody seems to do that.
There good reasons not to do that, e.g. save some CPU cycles and have deterministic behavior. See the discussion in the article above.

Since I never actually marketed that feature, its probably okay to remove that behavior. Any objectsions? Comments?

**Comment by Maaartinus** [comment]
The other thing is that randomized hashing can usually be cracked easily. That's why SipHash was invented.

Moreover, I'd bet that your `hashSeed` does not help at all. AFAIK the relation
```
modifiedHash(h1) & MASK == modifiedHash(h2) & MASK 
```
does not depend on `hashSeed`, which makes it rather pointless.

**Comment by cruftex** [comment]
@Maaartinus, yes you are right. The approach does not help much if at all. So I will remove it.

**Comment by hc-codersatlas** [comment]
Is there a way to disable this in the current version before it's removed in the code?

**Comment by cruftex** [comment]
@hc-codersatlas 
You can turn it off for all cache2k caches via a system property, e.g. by starting the JVM with the parameter:

````
-Dorg.cache2k.core.HeapCache.Tunable.disableHashRandomization=true
````

**Comment by hc-codersatlas** [comment]
Thanks, just never saw this in the documentation. All good.
