### ISSUE TITLE
Cache thread pool size exceeds the supplied executor's.

### ISSUE THREAD

**Issue by delta2wye** [cache2k/cache2k#99]
I'm supplying external `prefechExecutor` and `loaderExecutor` via the builder but the executors aren't getting used by the resulting `cache` when built.

Testcase: 
Use a shared loader executor with a fixed thread pool size to create multiple Caches.
Expected result: 
All caches use the same loader executor to load, not exceeding thread pool size (between all cache instances) specified by the said executor.
Observed result:
Thread dumps show that each Cache instance creates a default amount of threads regardless of the supplied executor.

**Comment by delta2wye** [comment]
There is no XML configuration in place.
Test code wrapper for cache creation:
`
    public class TestCache<K, V> {

        protected Cache<K, V> cache;
        private String name;
        private static final LinkedBlockingQueue<Runnable> PREFETCH_QUEUE = new LinkedBlockingQueue<>();
        private static final LinkedBlockingQueue<Runnable> LOADER_QUEUE = new LinkedBlockingQueue<>();
        private static final LinkedBlockingQueue<Runnable> LISTENER_QUEUE = new LinkedBlockingQueue<>();
        private static final ThreadPoolExecutor commonLoaderExecutor =
                new ThreadPoolExecutor(1, 1, 600L, TimeUnit.SECONDS, LOADER_QUEUE);
        private static final ThreadPoolExecutor prefetchExecutor =
                new ThreadPoolExecutor(1, 1, 600L, TimeUnit.SECONDS, PREFETCH_QUEUE);
        private static final ThreadPoolExecutor listenerExecutor =
                new ThreadPoolExecutor(1, 1, 600L, TimeUnit.SECONDS, LISTENER_QUEUE);

        private CacheFunnel(final String name,
                            final Class<K> keyType,
                            final Class<V> valueType,
                            final CacheLoader<K, V> loader,
                            final long expireAfterSeconds,
                            final long size) {
            this.name = name;

            cache = Cache2kBuilder.of(keyType, valueType)
                    .name(name)
                    .loader(new org.cache2k.integration.CacheLoader<K, V>() {
                        @Override
                        public V load(K key) throws Exception {
                            return loader.load(key);
                        }
                    })
                    .expireAfterWrite(expireAfterSeconds, TimeUnit.SECONDS)
                    .entryCapacity(size)
                    .permitNullValues(true)
                    .disableStatistics(true)
                    .boostConcurrency(true)
                    .storeByReference(true)
                    .prefetchExecutor(prefetchExecutor)
                    .loaderExecutor(commonLoaderExecutor)
                    .asyncListenerExecutor(listenerExecutor)
                    .build();
         }
    }
`

Note that the executors are static in this test with a max pool size of 1 each. When we create multiple instances of this cache, the expectation is that all instances of the TestCache will share the same three executors and the total threads will not exceed 3 (not counting any other threads needed for eviction/cleanup).

For the test, one cache instance is created. At this point, I see 16 threads dedicated to the cache instance, all in WAITING state from org.cache2k.core.util.SimpleTimer$TimerThread.run(SimpleTimer.java:337). This is my first concern. Why are there 16 threads for each cache instance. (Running on a 12 core machine).

Now, if we call `cacheInstance.get("somekey") from a different thread (call it thread "A"), I see the loader executing on thread "A" instead of the executor provided by the wrapper.

**Comment by cruftex** [comment]
> For the test, one cache instance is created. At this point, I see 16 threads dedicated to the cache instance, all in WAITING state from
> org.cache2k.core.util.SimpleTimer$TimerThread.run(SimpleTimer.java:337). This is my first concern. Why are there 16 threads for each cache instance. (Running on a 12 core machine).

One cache uses one timer thread in case there is an expiry value set by default. If you specify `boostCuncurrency(true)` then it will be more to avoid bottlenecks in updating the timer data structures and carrying out the actual expiry. On modern hardware I would think of that when there is more then one million updates per second. Only use it if you have evidence that the cache is a bottleneck, either by profiling or doing a comparing benchmark.

The same holds for `disableStatistics(true)`.

> Now, if we call `cacheInstance.get("somekey") from a different thread (call it thread "A"), I see the loader executing on thread "A" instead of the executor provided by the wrapper.

That is actually intended. `cache.get("somekey")` is a synchronous call, meaning that it needs to wait until a result is available. Because of that, the execution is in the calling thread. That spares one additional thread resource. The prefetch executor is used when `cache.prefetch()` or on expiry in case you also enable refresh ahead.

**Comment by cruftex** [comment]
Closing, since answered. The reported behavior seems due to the configuration.
Please feel free to comment if you have any further questions about it.
